/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessListService creates a new instance of MockAccessListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessListService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAccessListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAccessListService is an autogenerated mock type for the AccessListService type
type MockAccessListService struct {
	mock.Mock
}

type MockAccessListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessListService) EXPECT() *MockAccessListService_Expecter {
	return &MockAccessListService_Expecter{mock: &_m.Mock}
}

// AccessList provides a mock function for the type MockAccessListService
func (_mock *MockAccessListService) AccessList(ctx context.Context) (*adguard.AccessList, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AccessList")
	}

	var r0 *adguard.AccessList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.AccessList, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.AccessList); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.AccessList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessListService_AccessList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessList'
type MockAccessListService_AccessList_Call struct {
	*mock.Call
}

// AccessList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccessListService_Expecter) AccessList(ctx any) *MockAccessListService_AccessList_Call {
	return &MockAccessListService_AccessList_Call{Call: _e.mock.On("AccessList", ctx)}
}

func (_c *MockAccessListService_AccessList_Call) Run(run func(ctx context.Context)) *MockAccessListService_AccessList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccessListService_AccessList_Call) Return(accessList *adguard.AccessList, err error) *MockAccessListService_AccessList_Call {
	_c.Call.Return(accessList, err)
	return _c
}

func (_c *MockAccessListService_AccessList_Call) RunAndReturn(run func(ctx context.Context) (*adguard.AccessList, error)) *MockAccessListService_AccessList_Call {
	_c.Call.Return(run)
	return _c
}

// AccessSet provides a mock function for the type MockAccessListService
func (_mock *MockAccessListService) AccessSet(ctx context.Context, access adguard.AccessList) error {
	ret := _mock.Called(ctx, access)

	if len(ret) == 0 {
		panic("no return value specified for AccessSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.AccessList) error); ok {
		r0 = returnFunc(ctx, access)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccessListService_AccessSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessSet'
type MockAccessListService_AccessSet_Call struct {
	*mock.Call
}

// AccessSet is a helper method to define mock.On call
//   - ctx context.Context
//   - access adguard.AccessList
func (_e *MockAccessListService_Expecter) AccessSet(ctx any, access any) *MockAccessListService_AccessSet_Call {
	return &MockAccessListService_AccessSet_Call{Call: _e.mock.On("AccessSet", ctx, access)}
}

func (_c *MockAccessListService_AccessSet_Call) Run(run func(ctx context.Context, access adguard.AccessList)) *MockAccessListService_AccessSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.AccessList
		if args[1] != nil {
			arg1 = args[1].(adguard.AccessList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccessListService_AccessSet_Call) Return(err error) *MockAccessListService_AccessSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccessListService_AccessSet_Call) RunAndReturn(run func(ctx context.Context, access adguard.AccessList) error) *MockAccessListService_AccessSet_Call {
	_c.Call.Return(run)
	return _c
}
