/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockedServicesService creates a new instance of MockBlockedServicesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockedServicesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockedServicesService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBlockedServicesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBlockedServicesService is an autogenerated mock type for the BlockedServicesService type
type MockBlockedServicesService struct {
	mock.Mock
}

type MockBlockedServicesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockedServicesService) EXPECT() *MockBlockedServicesService_Expecter {
	return &MockBlockedServicesService_Expecter{mock: &_m.Mock}
}

// BlockedServicesAll provides a mock function for the type MockBlockedServicesService
func (_mock *MockBlockedServicesService) BlockedServicesAll(ctx context.Context) (*adguard.BlockedServicesAll, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BlockedServicesAll")
	}

	var r0 *adguard.BlockedServicesAll
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.BlockedServicesAll, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.BlockedServicesAll); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.BlockedServicesAll)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockedServicesService_BlockedServicesAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockedServicesAll'
type MockBlockedServicesService_BlockedServicesAll_Call struct {
	*mock.Call
}

// BlockedServicesAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlockedServicesService_Expecter) BlockedServicesAll(ctx any) *MockBlockedServicesService_BlockedServicesAll_Call {
	return &MockBlockedServicesService_BlockedServicesAll_Call{Call: _e.mock.On("BlockedServicesAll", ctx)}
}

func (_c *MockBlockedServicesService_BlockedServicesAll_Call) Run(run func(ctx context.Context)) *MockBlockedServicesService_BlockedServicesAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesAll_Call) Return(blockedServicesAll *adguard.BlockedServicesAll, err error) *MockBlockedServicesService_BlockedServicesAll_Call {
	_c.Call.Return(blockedServicesAll, err)
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesAll_Call) RunAndReturn(run func(ctx context.Context) (*adguard.BlockedServicesAll, error)) *MockBlockedServicesService_BlockedServicesAll_Call {
	_c.Call.Return(run)
	return _c
}

// BlockedServicesAvailableServices provides a mock function for the type MockBlockedServicesService
func (_mock *MockBlockedServicesService) BlockedServicesAvailableServices(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BlockedServicesAvailableServices")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockedServicesService_BlockedServicesAvailableServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockedServicesAvailableServices'
type MockBlockedServicesService_BlockedServicesAvailableServices_Call struct {
	*mock.Call
}

// BlockedServicesAvailableServices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlockedServicesService_Expecter) BlockedServicesAvailableServices(ctx any) *MockBlockedServicesService_BlockedServicesAvailableServices_Call {
	return &MockBlockedServicesService_BlockedServicesAvailableServices_Call{Call: _e.mock.On("BlockedServicesAvailableServices", ctx)}
}

func (_c *MockBlockedServicesService_BlockedServicesAvailableServices_Call) Run(run func(ctx context.Context)) *MockBlockedServicesService_BlockedServicesAvailableServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesAvailableServices_Call) Return(strings []string, err error) *MockBlockedServicesService_BlockedServicesAvailableServices_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesAvailableServices_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockBlockedServicesService_BlockedServicesAvailableServices_Call {
	_c.Call.Return(run)
	return _c
}

// BlockedServicesList provides a mock function for the type MockBlockedServicesService
func (_mock *MockBlockedServicesService) BlockedServicesList(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BlockedServicesList")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockedServicesService_BlockedServicesList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockedServicesList'
type MockBlockedServicesService_BlockedServicesList_Call struct {
	*mock.Call
}

// BlockedServicesList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlockedServicesService_Expecter) BlockedServicesList(ctx any) *MockBlockedServicesService_BlockedServicesList_Call {
	return &MockBlockedServicesService_BlockedServicesList_Call{Call: _e.mock.On("BlockedServicesList", ctx)}
}

func (_c *MockBlockedServicesService_BlockedServicesList_Call) Run(run func(ctx context.Context)) *MockBlockedServicesService_BlockedServicesList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesList_Call) Return(strings []string, err error) *MockBlockedServicesService_BlockedServicesList_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesList_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockBlockedServicesService_BlockedServicesList_Call {
	_c.Call.Return(run)
	return _c
}

// BlockedServicesSchedule provides a mock function for the type MockBlockedServicesService
func (_mock *MockBlockedServicesService) BlockedServicesSchedule(ctx context.Context) (*adguard.BlockedServicesSchedule, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BlockedServicesSchedule")
	}

	var r0 *adguard.BlockedServicesSchedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.BlockedServicesSchedule, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.BlockedServicesSchedule); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.BlockedServicesSchedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockedServicesService_BlockedServicesSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockedServicesSchedule'
type MockBlockedServicesService_BlockedServicesSchedule_Call struct {
	*mock.Call
}

// BlockedServicesSchedule is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlockedServicesService_Expecter) BlockedServicesSchedule(ctx any) *MockBlockedServicesService_BlockedServicesSchedule_Call {
	return &MockBlockedServicesService_BlockedServicesSchedule_Call{Call: _e.mock.On("BlockedServicesSchedule", ctx)}
}

func (_c *MockBlockedServicesService_BlockedServicesSchedule_Call) Run(run func(ctx context.Context)) *MockBlockedServicesService_BlockedServicesSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesSchedule_Call) Return(blockedServicesSchedule *adguard.BlockedServicesSchedule, err error) *MockBlockedServicesService_BlockedServicesSchedule_Call {
	_c.Call.Return(blockedServicesSchedule, err)
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesSchedule_Call) RunAndReturn(run func(ctx context.Context) (*adguard.BlockedServicesSchedule, error)) *MockBlockedServicesService_BlockedServicesSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// BlockedServicesScheduleUpdate provides a mock function for the type MockBlockedServicesService
func (_mock *MockBlockedServicesService) BlockedServicesScheduleUpdate(ctx context.Context, schedule adguard.BlockedServicesSchedule) error {
	ret := _mock.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for BlockedServicesScheduleUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.BlockedServicesSchedule) error); ok {
		r0 = returnFunc(ctx, schedule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockedServicesService_BlockedServicesScheduleUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockedServicesScheduleUpdate'
type MockBlockedServicesService_BlockedServicesScheduleUpdate_Call struct {
	*mock.Call
}

// BlockedServicesScheduleUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - schedule adguard.BlockedServicesSchedule
func (_e *MockBlockedServicesService_Expecter) BlockedServicesScheduleUpdate(ctx any, schedule any) *MockBlockedServicesService_BlockedServicesScheduleUpdate_Call {
	return &MockBlockedServicesService_BlockedServicesScheduleUpdate_Call{Call: _e.mock.On("BlockedServicesScheduleUpdate", ctx, schedule)}
}

func (_c *MockBlockedServicesService_BlockedServicesScheduleUpdate_Call) Run(run func(ctx context.Context, schedule adguard.BlockedServicesSchedule)) *MockBlockedServicesService_BlockedServicesScheduleUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.BlockedServicesSchedule
		if args[1] != nil {
			arg1 = args[1].(adguard.BlockedServicesSchedule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesScheduleUpdate_Call) Return(err error) *MockBlockedServicesService_BlockedServicesScheduleUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesScheduleUpdate_Call) RunAndReturn(run func(ctx context.Context, schedule adguard.BlockedServicesSchedule) error) *MockBlockedServicesService_BlockedServicesScheduleUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// BlockedServicesSet provides a mock function for the type MockBlockedServicesService
func (_mock *MockBlockedServicesService) BlockedServicesSet(ctx context.Context, services []string) error {
	ret := _mock.Called(ctx, services)

	if len(ret) == 0 {
		panic("no return value specified for BlockedServicesSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockedServicesService_BlockedServicesSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockedServicesSet'
type MockBlockedServicesService_BlockedServicesSet_Call struct {
	*mock.Call
}

// BlockedServicesSet is a helper method to define mock.On call
//   - ctx context.Context
//   - services []string
func (_e *MockBlockedServicesService_Expecter) BlockedServicesSet(ctx any, services any) *MockBlockedServicesService_BlockedServicesSet_Call {
	return &MockBlockedServicesService_BlockedServicesSet_Call{Call: _e.mock.On("BlockedServicesSet", ctx, services)}
}

func (_c *MockBlockedServicesService_BlockedServicesSet_Call) Run(run func(ctx context.Context, services []string)) *MockBlockedServicesService_BlockedServicesSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesSet_Call) Return(err error) *MockBlockedServicesService_BlockedServicesSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockedServicesService_BlockedServicesSet_Call) RunAndReturn(run func(ctx context.Context, services []string) error) *MockBlockedServicesService_BlockedServicesSet_Call {
	_c.Call.Return(run)
	return _c
}
