/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientsService creates a new instance of MockClientsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientsService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClientsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClientsService is an autogenerated mock type for the ClientsService type
type MockClientsService struct {
	mock.Mock
}

type MockClientsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientsService) EXPECT() *MockClientsService_Expecter {
	return &MockClientsService_Expecter{mock: &_m.Mock}
}

// ClientsAdd provides a mock function for the type MockClientsService
func (_mock *MockClientsService) ClientsAdd(ctx context.Context, config adguard.ClientConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for ClientsAdd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.ClientConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientsService_ClientsAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientsAdd'
type MockClientsService_ClientsAdd_Call struct {
	*mock.Call
}

// ClientsAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.ClientConfig
func (_e *MockClientsService_Expecter) ClientsAdd(ctx any, config any) *MockClientsService_ClientsAdd_Call {
	return &MockClientsService_ClientsAdd_Call{Call: _e.mock.On("ClientsAdd", ctx, config)}
}

func (_c *MockClientsService_ClientsAdd_Call) Run(run func(ctx context.Context, config adguard.ClientConfig)) *MockClientsService_ClientsAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.ClientConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.ClientConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientsService_ClientsAdd_Call) Return(err error) *MockClientsService_ClientsAdd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientsService_ClientsAdd_Call) RunAndReturn(run func(ctx context.Context, config adguard.ClientConfig) error) *MockClientsService_ClientsAdd_Call {
	_c.Call.Return(run)
	return _c
}

// ClientsDelete provides a mock function for the type MockClientsService
func (_mock *MockClientsService) ClientsDelete(ctx context.Context, request adguard.ClientDelete) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ClientsDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.ClientDelete) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientsService_ClientsDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientsDelete'
type MockClientsService_ClientsDelete_Call struct {
	*mock.Call
}

// ClientsDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.ClientDelete
func (_e *MockClientsService_Expecter) ClientsDelete(ctx any, request any) *MockClientsService_ClientsDelete_Call {
	return &MockClientsService_ClientsDelete_Call{Call: _e.mock.On("ClientsDelete", ctx, request)}
}

func (_c *MockClientsService_ClientsDelete_Call) Run(run func(ctx context.Context, request adguard.ClientDelete)) *MockClientsService_ClientsDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.ClientDelete
		if args[1] != nil {
			arg1 = args[1].(adguard.ClientDelete)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientsService_ClientsDelete_Call) Return(err error) *MockClientsService_ClientsDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientsService_ClientsDelete_Call) RunAndReturn(run func(ctx context.Context, request adguard.ClientDelete) error) *MockClientsService_ClientsDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ClientsFind provides a mock function for the type MockClientsService
func (_mock *MockClientsService) ClientsFind(ctx context.Context, ids ...string) ([]adguard.ClientFindEntry, error) {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, ids)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ClientsFind")
	}

	var r0 []adguard.ClientFindEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]adguard.ClientFindEntry, error)); ok {
		return returnFunc(ctx, ids...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []adguard.ClientFindEntry); ok {
		r0 = returnFunc(ctx, ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adguard.ClientFindEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, ids...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientsService_ClientsFind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientsFind'
type MockClientsService_ClientsFind_Call struct {
	*mock.Call
}

// ClientsFind is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...string
func (_e *MockClientsService_Expecter) ClientsFind(ctx any, ids ...any) *MockClientsService_ClientsFind_Call {
	return &MockClientsService_ClientsFind_Call{Call: _e.mock.On("ClientsFind",
		append([]any{ctx}, ids...)...)}
}

func (_c *MockClientsService_ClientsFind_Call) Run(run func(ctx context.Context, ids ...string)) *MockClientsService_ClientsFind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClientsService_ClientsFind_Call) Return(clientFindEntrys []adguard.ClientFindEntry, err error) *MockClientsService_ClientsFind_Call {
	_c.Call.Return(clientFindEntrys, err)
	return _c
}

func (_c *MockClientsService_ClientsFind_Call) RunAndReturn(run func(ctx context.Context, ids ...string) ([]adguard.ClientFindEntry, error)) *MockClientsService_ClientsFind_Call {
	_c.Call.Return(run)
	return _c
}

// ClientsSearch provides a mock function for the type MockClientsService
func (_mock *MockClientsService) ClientsSearch(ctx context.Context, request adguard.ClientsSearchRequest) ([]adguard.ClientFindEntry, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ClientsSearch")
	}

	var r0 []adguard.ClientFindEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.ClientsSearchRequest) ([]adguard.ClientFindEntry, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.ClientsSearchRequest) []adguard.ClientFindEntry); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adguard.ClientFindEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.ClientsSearchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientsService_ClientsSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientsSearch'
type MockClientsService_ClientsSearch_Call struct {
	*mock.Call
}

// ClientsSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.ClientsSearchRequest
func (_e *MockClientsService_Expecter) ClientsSearch(ctx any, request any) *MockClientsService_ClientsSearch_Call {
	return &MockClientsService_ClientsSearch_Call{Call: _e.mock.On("ClientsSearch", ctx, request)}
}

func (_c *MockClientsService_ClientsSearch_Call) Run(run func(ctx context.Context, request adguard.ClientsSearchRequest)) *MockClientsService_ClientsSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.ClientsSearchRequest
		if args[1] != nil {
			arg1 = args[1].(adguard.ClientsSearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientsService_ClientsSearch_Call) Return(clientFindEntrys []adguard.ClientFindEntry, err error) *MockClientsService_ClientsSearch_Call {
	_c.Call.Return(clientFindEntrys, err)
	return _c
}

func (_c *MockClientsService_ClientsSearch_Call) RunAndReturn(run func(ctx context.Context, request adguard.ClientsSearchRequest) ([]adguard.ClientFindEntry, error)) *MockClientsService_ClientsSearch_Call {
	_c.Call.Return(run)
	return _c
}

// ClientsStatus provides a mock function for the type MockClientsService
func (_mock *MockClientsService) ClientsStatus(ctx context.Context) (*adguard.ClientsStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClientsStatus")
	}

	var r0 *adguard.ClientsStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.ClientsStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.ClientsStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.ClientsStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientsService_ClientsStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientsStatus'
type MockClientsService_ClientsStatus_Call struct {
	*mock.Call
}

// ClientsStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientsService_Expecter) ClientsStatus(ctx any) *MockClientsService_ClientsStatus_Call {
	return &MockClientsService_ClientsStatus_Call{Call: _e.mock.On("ClientsStatus", ctx)}
}

func (_c *MockClientsService_ClientsStatus_Call) Run(run func(ctx context.Context)) *MockClientsService_ClientsStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientsService_ClientsStatus_Call) Return(clientsStatus *adguard.ClientsStatus, err error) *MockClientsService_ClientsStatus_Call {
	_c.Call.Return(clientsStatus, err)
	return _c
}

func (_c *MockClientsService_ClientsStatus_Call) RunAndReturn(run func(ctx context.Context) (*adguard.ClientsStatus, error)) *MockClientsService_ClientsStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ClientsUpdate provides a mock function for the type MockClientsService
func (_mock *MockClientsService) ClientsUpdate(ctx context.Context, request adguard.ClientUpdate) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ClientsUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.ClientUpdate) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientsService_ClientsUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientsUpdate'
type MockClientsService_ClientsUpdate_Call struct {
	*mock.Call
}

// ClientsUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.ClientUpdate
func (_e *MockClientsService_Expecter) ClientsUpdate(ctx any, request any) *MockClientsService_ClientsUpdate_Call {
	return &MockClientsService_ClientsUpdate_Call{Call: _e.mock.On("ClientsUpdate", ctx, request)}
}

func (_c *MockClientsService_ClientsUpdate_Call) Run(run func(ctx context.Context, request adguard.ClientUpdate)) *MockClientsService_ClientsUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.ClientUpdate
		if args[1] != nil {
			arg1 = args[1].(adguard.ClientUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientsService_ClientsUpdate_Call) Return(err error) *MockClientsService_ClientsUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientsService_ClientsUpdate_Call) RunAndReturn(run func(ctx context.Context, request adguard.ClientUpdate) error) *MockClientsService_ClientsUpdate_Call {
	_c.Call.Return(run)
	return _c
}
