/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDHCPService creates a new instance of MockDHCPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDHCPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDHCPService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDHCPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDHCPService is an autogenerated mock type for the DHCPService type
type MockDHCPService struct {
	mock.Mock
}

type MockDHCPService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDHCPService) EXPECT() *MockDHCPService_Expecter {
	return &MockDHCPService_Expecter{mock: &_m.Mock}
}

// DHCPAddStaticLease provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPAddStaticLease(ctx context.Context, lease adguard.DHCPStaticLease) error {
	ret := _mock.Called(ctx, lease)

	if len(ret) == 0 {
		panic("no return value specified for DHCPAddStaticLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.DHCPStaticLease) error); ok {
		r0 = returnFunc(ctx, lease)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHCPService_DHCPAddStaticLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPAddStaticLease'
type MockDHCPService_DHCPAddStaticLease_Call struct {
	*mock.Call
}

// DHCPAddStaticLease is a helper method to define mock.On call
//   - ctx context.Context
//   - lease adguard.DHCPStaticLease
func (_e *MockDHCPService_Expecter) DHCPAddStaticLease(ctx any, lease any) *MockDHCPService_DHCPAddStaticLease_Call {
	return &MockDHCPService_DHCPAddStaticLease_Call{Call: _e.mock.On("DHCPAddStaticLease", ctx, lease)}
}

func (_c *MockDHCPService_DHCPAddStaticLease_Call) Run(run func(ctx context.Context, lease adguard.DHCPStaticLease)) *MockDHCPService_DHCPAddStaticLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.DHCPStaticLease
		if args[1] != nil {
			arg1 = args[1].(adguard.DHCPStaticLease)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPAddStaticLease_Call) Return(err error) *MockDHCPService_DHCPAddStaticLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHCPService_DHCPAddStaticLease_Call) RunAndReturn(run func(ctx context.Context, lease adguard.DHCPStaticLease) error) *MockDHCPService_DHCPAddStaticLease_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPConfig provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPConfig(ctx context.Context, config *adguard.DHCPConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for DHCPConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.DHCPConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHCPService_DHCPConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPConfig'
type MockDHCPService_DHCPConfig_Call struct {
	*mock.Call
}

// DHCPConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config *adguard.DHCPConfig
func (_e *MockDHCPService_Expecter) DHCPConfig(ctx any, config any) *MockDHCPService_DHCPConfig_Call {
	return &MockDHCPService_DHCPConfig_Call{Call: _e.mock.On("DHCPConfig", ctx, config)}
}

func (_c *MockDHCPService_DHCPConfig_Call) Run(run func(ctx context.Context, config *adguard.DHCPConfig)) *MockDHCPService_DHCPConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.DHCPConfig
		if args[1] != nil {
			arg1 = args[1].(*adguard.DHCPConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPConfig_Call) Return(err error) *MockDHCPService_DHCPConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHCPService_DHCPConfig_Call) RunAndReturn(run func(ctx context.Context, config *adguard.DHCPConfig) error) *MockDHCPService_DHCPConfig_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPFindActive provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPFindActive(ctx context.Context, request *adguard.DHCPFindRequest) (*adguard.DHCPFindResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DHCPFindActive")
	}

	var r0 *adguard.DHCPFindResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.DHCPFindRequest) (*adguard.DHCPFindResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.DHCPFindRequest) *adguard.DHCPFindResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.DHCPFindResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *adguard.DHCPFindRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDHCPService_DHCPFindActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPFindActive'
type MockDHCPService_DHCPFindActive_Call struct {
	*mock.Call
}

// DHCPFindActive is a helper method to define mock.On call
//   - ctx context.Context
//   - request *adguard.DHCPFindRequest
func (_e *MockDHCPService_Expecter) DHCPFindActive(ctx any, request any) *MockDHCPService_DHCPFindActive_Call {
	return &MockDHCPService_DHCPFindActive_Call{Call: _e.mock.On("DHCPFindActive", ctx, request)}
}

func (_c *MockDHCPService_DHCPFindActive_Call) Run(run func(ctx context.Context, request *adguard.DHCPFindRequest)) *MockDHCPService_DHCPFindActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.DHCPFindRequest
		if args[1] != nil {
			arg1 = args[1].(*adguard.DHCPFindRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPFindActive_Call) Return(dHCPFindResult *adguard.DHCPFindResult, err error) *MockDHCPService_DHCPFindActive_Call {
	_c.Call.Return(dHCPFindResult, err)
	return _c
}

func (_c *MockDHCPService_DHCPFindActive_Call) RunAndReturn(run func(ctx context.Context, request *adguard.DHCPFindRequest) (*adguard.DHCPFindResult, error)) *MockDHCPService_DHCPFindActive_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPInterfaces provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPInterfaces(ctx context.Context) (map[string]adguard.DHCPInterface, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DHCPInterfaces")
	}

	var r0 map[string]adguard.DHCPInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]adguard.DHCPInterface, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]adguard.DHCPInterface); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]adguard.DHCPInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDHCPService_DHCPInterfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPInterfaces'
type MockDHCPService_DHCPInterfaces_Call struct {
	*mock.Call
}

// DHCPInterfaces is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDHCPService_Expecter) DHCPInterfaces(ctx any) *MockDHCPService_DHCPInterfaces_Call {
	return &MockDHCPService_DHCPInterfaces_Call{Call: _e.mock.On("DHCPInterfaces", ctx)}
}

func (_c *MockDHCPService_DHCPInterfaces_Call) Run(run func(ctx context.Context)) *MockDHCPService_DHCPInterfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPInterfaces_Call) Return(stringToDHCPInterface map[string]adguard.DHCPInterface, err error) *MockDHCPService_DHCPInterfaces_Call {
	_c.Call.Return(stringToDHCPInterface, err)
	return _c
}

func (_c *MockDHCPService_DHCPInterfaces_Call) RunAndReturn(run func(ctx context.Context) (map[string]adguard.DHCPInterface, error)) *MockDHCPService_DHCPInterfaces_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPRemoveStaticLease provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPRemoveStaticLease(ctx context.Context, lease adguard.DHCPStaticLease) error {
	ret := _mock.Called(ctx, lease)

	if len(ret) == 0 {
		panic("no return value specified for DHCPRemoveStaticLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.DHCPStaticLease) error); ok {
		r0 = returnFunc(ctx, lease)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHCPService_DHCPRemoveStaticLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPRemoveStaticLease'
type MockDHCPService_DHCPRemoveStaticLease_Call struct {
	*mock.Call
}

// DHCPRemoveStaticLease is a helper method to define mock.On call
//   - ctx context.Context
//   - lease adguard.DHCPStaticLease
func (_e *MockDHCPService_Expecter) DHCPRemoveStaticLease(ctx any, lease any) *MockDHCPService_DHCPRemoveStaticLease_Call {
	return &MockDHCPService_DHCPRemoveStaticLease_Call{Call: _e.mock.On("DHCPRemoveStaticLease", ctx, lease)}
}

func (_c *MockDHCPService_DHCPRemoveStaticLease_Call) Run(run func(ctx context.Context, lease adguard.DHCPStaticLease)) *MockDHCPService_DHCPRemoveStaticLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.DHCPStaticLease
		if args[1] != nil {
			arg1 = args[1].(adguard.DHCPStaticLease)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPRemoveStaticLease_Call) Return(err error) *MockDHCPService_DHCPRemoveStaticLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHCPService_DHCPRemoveStaticLease_Call) RunAndReturn(run func(ctx context.Context, lease adguard.DHCPStaticLease) error) *MockDHCPService_DHCPRemoveStaticLease_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPReset provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPReset(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DHCPReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHCPService_DHCPReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPReset'
type MockDHCPService_DHCPReset_Call struct {
	*mock.Call
}

// DHCPReset is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDHCPService_Expecter) DHCPReset(ctx any) *MockDHCPService_DHCPReset_Call {
	return &MockDHCPService_DHCPReset_Call{Call: _e.mock.On("DHCPReset", ctx)}
}

func (_c *MockDHCPService_DHCPReset_Call) Run(run func(ctx context.Context)) *MockDHCPService_DHCPReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPReset_Call) Return(err error) *MockDHCPService_DHCPReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHCPService_DHCPReset_Call) RunAndReturn(run func(ctx context.Context) error) *MockDHCPService_DHCPReset_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPResetLeases provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPResetLeases(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DHCPResetLeases")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHCPService_DHCPResetLeases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPResetLeases'
type MockDHCPService_DHCPResetLeases_Call struct {
	*mock.Call
}

// DHCPResetLeases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDHCPService_Expecter) DHCPResetLeases(ctx any) *MockDHCPService_DHCPResetLeases_Call {
	return &MockDHCPService_DHCPResetLeases_Call{Call: _e.mock.On("DHCPResetLeases", ctx)}
}

func (_c *MockDHCPService_DHCPResetLeases_Call) Run(run func(ctx context.Context)) *MockDHCPService_DHCPResetLeases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPResetLeases_Call) Return(err error) *MockDHCPService_DHCPResetLeases_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHCPService_DHCPResetLeases_Call) RunAndReturn(run func(ctx context.Context) error) *MockDHCPService_DHCPResetLeases_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPStatus provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPStatus(ctx context.Context) (*adguard.DHCPStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DHCPStatus")
	}

	var r0 *adguard.DHCPStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.DHCPStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.DHCPStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.DHCPStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDHCPService_DHCPStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPStatus'
type MockDHCPService_DHCPStatus_Call struct {
	*mock.Call
}

// DHCPStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDHCPService_Expecter) DHCPStatus(ctx any) *MockDHCPService_DHCPStatus_Call {
	return &MockDHCPService_DHCPStatus_Call{Call: _e.mock.On("DHCPStatus", ctx)}
}

func (_c *MockDHCPService_DHCPStatus_Call) Run(run func(ctx context.Context)) *MockDHCPService_DHCPStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPStatus_Call) Return(dHCPStatus *adguard.DHCPStatus, err error) *MockDHCPService_DHCPStatus_Call {
	_c.Call.Return(dHCPStatus, err)
	return _c
}

func (_c *MockDHCPService_DHCPStatus_Call) RunAndReturn(run func(ctx context.Context) (*adguard.DHCPStatus, error)) *MockDHCPService_DHCPStatus_Call {
	_c.Call.Return(run)
	return _c
}

// DHCPUpdateStaticLease provides a mock function for the type MockDHCPService
func (_mock *MockDHCPService) DHCPUpdateStaticLease(ctx context.Context, lease adguard.DHCPStaticLease) error {
	ret := _mock.Called(ctx, lease)

	if len(ret) == 0 {
		panic("no return value specified for DHCPUpdateStaticLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.DHCPStaticLease) error); ok {
		r0 = returnFunc(ctx, lease)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDHCPService_DHCPUpdateStaticLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DHCPUpdateStaticLease'
type MockDHCPService_DHCPUpdateStaticLease_Call struct {
	*mock.Call
}

// DHCPUpdateStaticLease is a helper method to define mock.On call
//   - ctx context.Context
//   - lease adguard.DHCPStaticLease
func (_e *MockDHCPService_Expecter) DHCPUpdateStaticLease(ctx any, lease any) *MockDHCPService_DHCPUpdateStaticLease_Call {
	return &MockDHCPService_DHCPUpdateStaticLease_Call{Call: _e.mock.On("DHCPUpdateStaticLease", ctx, lease)}
}

func (_c *MockDHCPService_DHCPUpdateStaticLease_Call) Run(run func(ctx context.Context, lease adguard.DHCPStaticLease)) *MockDHCPService_DHCPUpdateStaticLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.DHCPStaticLease
		if args[1] != nil {
			arg1 = args[1].(adguard.DHCPStaticLease)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDHCPService_DHCPUpdateStaticLease_Call) Return(err error) *MockDHCPService_DHCPUpdateStaticLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDHCPService_DHCPUpdateStaticLease_Call) RunAndReturn(run func(ctx context.Context, lease adguard.DHCPStaticLease) error) *MockDHCPService_DHCPUpdateStaticLease_Call {
	_c.Call.Return(run)
	return _c
}
