/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDNSService creates a new instance of MockDNSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDNSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDNSService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDNSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDNSService is an autogenerated mock type for the DNSService type
type MockDNSService struct {
	mock.Mock
}

type MockDNSService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDNSService) EXPECT() *MockDNSService_Expecter {
	return &MockDNSService_Expecter{mock: &_m.Mock}
}

// DNSInfo provides a mock function for the type MockDNSService
func (_mock *MockDNSService) DNSInfo(ctx context.Context) (*adguard.DNSConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DNSInfo")
	}

	var r0 *adguard.DNSConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.DNSConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.DNSConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.DNSConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_DNSInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DNSInfo'
type MockDNSService_DNSInfo_Call struct {
	*mock.Call
}

// DNSInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDNSService_Expecter) DNSInfo(ctx any) *MockDNSService_DNSInfo_Call {
	return &MockDNSService_DNSInfo_Call{Call: _e.mock.On("DNSInfo", ctx)}
}

func (_c *MockDNSService_DNSInfo_Call) Run(run func(ctx context.Context)) *MockDNSService_DNSInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDNSService_DNSInfo_Call) Return(dNSConfig *adguard.DNSConfig, err error) *MockDNSService_DNSInfo_Call {
	_c.Call.Return(dNSConfig, err)
	return _c
}

func (_c *MockDNSService_DNSInfo_Call) RunAndReturn(run func(ctx context.Context) (*adguard.DNSConfig, error)) *MockDNSService_DNSInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SetDNSConfig provides a mock function for the type MockDNSService
func (_mock *MockDNSService) SetDNSConfig(ctx context.Context, config *adguard.DNSConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for SetDNSConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.DNSConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDNSService_SetDNSConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDNSConfig'
type MockDNSService_SetDNSConfig_Call struct {
	*mock.Call
}

// SetDNSConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config *adguard.DNSConfig
func (_e *MockDNSService_Expecter) SetDNSConfig(ctx any, config any) *MockDNSService_SetDNSConfig_Call {
	return &MockDNSService_SetDNSConfig_Call{Call: _e.mock.On("SetDNSConfig", ctx, config)}
}

func (_c *MockDNSService_SetDNSConfig_Call) Run(run func(ctx context.Context, config *adguard.DNSConfig)) *MockDNSService_SetDNSConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.DNSConfig
		if args[1] != nil {
			arg1 = args[1].(*adguard.DNSConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_SetDNSConfig_Call) Return(err error) *MockDNSService_SetDNSConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDNSService_SetDNSConfig_Call) RunAndReturn(run func(ctx context.Context, config *adguard.DNSConfig) error) *MockDNSService_SetDNSConfig_Call {
	_c.Call.Return(run)
	return _c
}

// TestUpstreamDNS provides a mock function for the type MockDNSService
func (_mock *MockDNSService) TestUpstreamDNS(ctx context.Context, config adguard.UpstreamConfig) (map[string]string, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestUpstreamDNS")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.UpstreamConfig) (map[string]string, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.UpstreamConfig) map[string]string); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.UpstreamConfig) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSService_TestUpstreamDNS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestUpstreamDNS'
type MockDNSService_TestUpstreamDNS_Call struct {
	*mock.Call
}

// TestUpstreamDNS is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.UpstreamConfig
func (_e *MockDNSService_Expecter) TestUpstreamDNS(ctx any, config any) *MockDNSService_TestUpstreamDNS_Call {
	return &MockDNSService_TestUpstreamDNS_Call{Call: _e.mock.On("TestUpstreamDNS", ctx, config)}
}

func (_c *MockDNSService_TestUpstreamDNS_Call) Run(run func(ctx context.Context, config adguard.UpstreamConfig)) *MockDNSService_TestUpstreamDNS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.UpstreamConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.UpstreamConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDNSService_TestUpstreamDNS_Call) Return(stringToString map[string]string, err error) *MockDNSService_TestUpstreamDNS_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockDNSService_TestUpstreamDNS_Call) RunAndReturn(run func(ctx context.Context, config adguard.UpstreamConfig) (map[string]string, error)) *MockDNSService_TestUpstreamDNS_Call {
	_c.Call.Return(run)
	return _c
}
