/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFilteringService creates a new instance of MockFilteringService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilteringService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilteringService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFilteringService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFilteringService is an autogenerated mock type for the FilteringService type
type MockFilteringService struct {
	mock.Mock
}

type MockFilteringService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilteringService) EXPECT() *MockFilteringService_Expecter {
	return &MockFilteringService_Expecter{mock: &_m.Mock}
}

// AddFilteringURL provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) AddFilteringURL(ctx context.Context, request adguard.AddFilteringURLRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for AddFilteringURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.AddFilteringURLRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFilteringService_AddFilteringURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFilteringURL'
type MockFilteringService_AddFilteringURL_Call struct {
	*mock.Call
}

// AddFilteringURL is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.AddFilteringURLRequest
func (_e *MockFilteringService_Expecter) AddFilteringURL(ctx any, request any) *MockFilteringService_AddFilteringURL_Call {
	return &MockFilteringService_AddFilteringURL_Call{Call: _e.mock.On("AddFilteringURL", ctx, request)}
}

func (_c *MockFilteringService_AddFilteringURL_Call) Run(run func(ctx context.Context, request adguard.AddFilteringURLRequest)) *MockFilteringService_AddFilteringURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.AddFilteringURLRequest
		if args[1] != nil {
			arg1 = args[1].(adguard.AddFilteringURLRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilteringService_AddFilteringURL_Call) Return(err error) *MockFilteringService_AddFilteringURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFilteringService_AddFilteringURL_Call) RunAndReturn(run func(ctx context.Context, request adguard.AddFilteringURLRequest) error) *MockFilteringService_AddFilteringURL_Call {
	_c.Call.Return(run)
	return _c
}

// CheckFilteredHost provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) CheckFilteredHost(ctx context.Context, request adguard.CheckHostRequest) (*adguard.FilteredHostResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CheckFilteredHost")
	}

	var r0 *adguard.FilteredHostResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.CheckHostRequest) (*adguard.FilteredHostResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.CheckHostRequest) *adguard.FilteredHostResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.FilteredHostResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.CheckHostRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilteringService_CheckFilteredHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckFilteredHost'
type MockFilteringService_CheckFilteredHost_Call struct {
	*mock.Call
}

// CheckFilteredHost is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.CheckHostRequest
func (_e *MockFilteringService_Expecter) CheckFilteredHost(ctx any, request any) *MockFilteringService_CheckFilteredHost_Call {
	return &MockFilteringService_CheckFilteredHost_Call{Call: _e.mock.On("CheckFilteredHost", ctx, request)}
}

func (_c *MockFilteringService_CheckFilteredHost_Call) Run(run func(ctx context.Context, request adguard.CheckHostRequest)) *MockFilteringService_CheckFilteredHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.CheckHostRequest
		if args[1] != nil {
			arg1 = args[1].(adguard.CheckHostRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilteringService_CheckFilteredHost_Call) Return(filteredHostResult *adguard.FilteredHostResult, err error) *MockFilteringService_CheckFilteredHost_Call {
	_c.Call.Return(filteredHostResult, err)
	return _c
}

func (_c *MockFilteringService_CheckFilteredHost_Call) RunAndReturn(run func(ctx context.Context, request adguard.CheckHostRequest) (*adguard.FilteredHostResult, error)) *MockFilteringService_CheckFilteredHost_Call {
	_c.Call.Return(run)
	return _c
}

// FilteringStatus provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) FilteringStatus(ctx context.Context) (*adguard.FilteringStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FilteringStatus")
	}

	var r0 *adguard.FilteringStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.FilteringStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.FilteringStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.FilteringStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilteringService_FilteringStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilteringStatus'
type MockFilteringService_FilteringStatus_Call struct {
	*mock.Call
}

// FilteringStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFilteringService_Expecter) FilteringStatus(ctx any) *MockFilteringService_FilteringStatus_Call {
	return &MockFilteringService_FilteringStatus_Call{Call: _e.mock.On("FilteringStatus", ctx)}
}

func (_c *MockFilteringService_FilteringStatus_Call) Run(run func(ctx context.Context)) *MockFilteringService_FilteringStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFilteringService_FilteringStatus_Call) Return(filteringStatus *adguard.FilteringStatus, err error) *MockFilteringService_FilteringStatus_Call {
	_c.Call.Return(filteringStatus, err)
	return _c
}

func (_c *MockFilteringService_FilteringStatus_Call) RunAndReturn(run func(ctx context.Context) (*adguard.FilteringStatus, error)) *MockFilteringService_FilteringStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshFiltering provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) RefreshFiltering(ctx context.Context, request *adguard.RefreshFilteringRequest) (*adguard.FilteringRefreshResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RefreshFiltering")
	}

	var r0 *adguard.FilteringRefreshResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.RefreshFilteringRequest) (*adguard.FilteringRefreshResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.RefreshFilteringRequest) *adguard.FilteringRefreshResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.FilteringRefreshResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *adguard.RefreshFilteringRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilteringService_RefreshFiltering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshFiltering'
type MockFilteringService_RefreshFiltering_Call struct {
	*mock.Call
}

// RefreshFiltering is a helper method to define mock.On call
//   - ctx context.Context
//   - request *adguard.RefreshFilteringRequest
func (_e *MockFilteringService_Expecter) RefreshFiltering(ctx any, request any) *MockFilteringService_RefreshFiltering_Call {
	return &MockFilteringService_RefreshFiltering_Call{Call: _e.mock.On("RefreshFiltering", ctx, request)}
}

func (_c *MockFilteringService_RefreshFiltering_Call) Run(run func(ctx context.Context, request *adguard.RefreshFilteringRequest)) *MockFilteringService_RefreshFiltering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.RefreshFilteringRequest
		if args[1] != nil {
			arg1 = args[1].(*adguard.RefreshFilteringRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilteringService_RefreshFiltering_Call) Return(filteringRefreshResult *adguard.FilteringRefreshResult, err error) *MockFilteringService_RefreshFiltering_Call {
	_c.Call.Return(filteringRefreshResult, err)
	return _c
}

func (_c *MockFilteringService_RefreshFiltering_Call) RunAndReturn(run func(ctx context.Context, request *adguard.RefreshFilteringRequest) (*adguard.FilteringRefreshResult, error)) *MockFilteringService_RefreshFiltering_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFilteringURL provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) RemoveFilteringURL(ctx context.Context, request adguard.RemoveFilteringURLRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFilteringURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.RemoveFilteringURLRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFilteringService_RemoveFilteringURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFilteringURL'
type MockFilteringService_RemoveFilteringURL_Call struct {
	*mock.Call
}

// RemoveFilteringURL is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.RemoveFilteringURLRequest
func (_e *MockFilteringService_Expecter) RemoveFilteringURL(ctx any, request any) *MockFilteringService_RemoveFilteringURL_Call {
	return &MockFilteringService_RemoveFilteringURL_Call{Call: _e.mock.On("RemoveFilteringURL", ctx, request)}
}

func (_c *MockFilteringService_RemoveFilteringURL_Call) Run(run func(ctx context.Context, request adguard.RemoveFilteringURLRequest)) *MockFilteringService_RemoveFilteringURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.RemoveFilteringURLRequest
		if args[1] != nil {
			arg1 = args[1].(adguard.RemoveFilteringURLRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilteringService_RemoveFilteringURL_Call) Return(err error) *MockFilteringService_RemoveFilteringURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFilteringService_RemoveFilteringURL_Call) RunAndReturn(run func(ctx context.Context, request adguard.RemoveFilteringURLRequest) error) *MockFilteringService_RemoveFilteringURL_Call {
	_c.Call.Return(run)
	return _c
}

// SetFilteringRules provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) SetFilteringRules(ctx context.Context, request *adguard.SetFilteringRulesRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SetFilteringRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.SetFilteringRulesRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFilteringService_SetFilteringRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFilteringRules'
type MockFilteringService_SetFilteringRules_Call struct {
	*mock.Call
}

// SetFilteringRules is a helper method to define mock.On call
//   - ctx context.Context
//   - request *adguard.SetFilteringRulesRequest
func (_e *MockFilteringService_Expecter) SetFilteringRules(ctx any, request any) *MockFilteringService_SetFilteringRules_Call {
	return &MockFilteringService_SetFilteringRules_Call{Call: _e.mock.On("SetFilteringRules", ctx, request)}
}

func (_c *MockFilteringService_SetFilteringRules_Call) Run(run func(ctx context.Context, request *adguard.SetFilteringRulesRequest)) *MockFilteringService_SetFilteringRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.SetFilteringRulesRequest
		if args[1] != nil {
			arg1 = args[1].(*adguard.SetFilteringRulesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilteringService_SetFilteringRules_Call) Return(err error) *MockFilteringService_SetFilteringRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFilteringService_SetFilteringRules_Call) RunAndReturn(run func(ctx context.Context, request *adguard.SetFilteringRulesRequest) error) *MockFilteringService_SetFilteringRules_Call {
	_c.Call.Return(run)
	return _c
}

// SetFilteringURL provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) SetFilteringURL(ctx context.Context, request *adguard.SetFilteringURLRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SetFilteringURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.SetFilteringURLRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFilteringService_SetFilteringURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFilteringURL'
type MockFilteringService_SetFilteringURL_Call struct {
	*mock.Call
}

// SetFilteringURL is a helper method to define mock.On call
//   - ctx context.Context
//   - request *adguard.SetFilteringURLRequest
func (_e *MockFilteringService_Expecter) SetFilteringURL(ctx any, request any) *MockFilteringService_SetFilteringURL_Call {
	return &MockFilteringService_SetFilteringURL_Call{Call: _e.mock.On("SetFilteringURL", ctx, request)}
}

func (_c *MockFilteringService_SetFilteringURL_Call) Run(run func(ctx context.Context, request *adguard.SetFilteringURLRequest)) *MockFilteringService_SetFilteringURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.SetFilteringURLRequest
		if args[1] != nil {
			arg1 = args[1].(*adguard.SetFilteringURLRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilteringService_SetFilteringURL_Call) Return(err error) *MockFilteringService_SetFilteringURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFilteringService_SetFilteringURL_Call) RunAndReturn(run func(ctx context.Context, request *adguard.SetFilteringURLRequest) error) *MockFilteringService_SetFilteringURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFilteringConfig provides a mock function for the type MockFilteringService
func (_mock *MockFilteringService) UpdateFilteringConfig(ctx context.Context, config adguard.FilteringConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFilteringConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.FilteringConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFilteringService_UpdateFilteringConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFilteringConfig'
type MockFilteringService_UpdateFilteringConfig_Call struct {
	*mock.Call
}

// UpdateFilteringConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.FilteringConfig
func (_e *MockFilteringService_Expecter) UpdateFilteringConfig(ctx any, config any) *MockFilteringService_UpdateFilteringConfig_Call {
	return &MockFilteringService_UpdateFilteringConfig_Call{Call: _e.mock.On("UpdateFilteringConfig", ctx, config)}
}

func (_c *MockFilteringService_UpdateFilteringConfig_Call) Run(run func(ctx context.Context, config adguard.FilteringConfig)) *MockFilteringService_UpdateFilteringConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.FilteringConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.FilteringConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilteringService_UpdateFilteringConfig_Call) Return(err error) *MockFilteringService_UpdateFilteringConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFilteringService_UpdateFilteringConfig_Call) RunAndReturn(run func(ctx context.Context, config adguard.FilteringConfig) error) *MockFilteringService_UpdateFilteringConfig_Call {
	_c.Call.Return(run)
	return _c
}
