/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInstallService creates a new instance of MockInstallService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInstallService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInstallService is an autogenerated mock type for the InstallService type
type MockInstallService struct {
	mock.Mock
}

type MockInstallService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallService) EXPECT() *MockInstallService_Expecter {
	return &MockInstallService_Expecter{mock: &_m.Mock}
}

// InstallCheckConfig provides a mock function for the type MockInstallService
func (_mock *MockInstallService) InstallCheckConfig(ctx context.Context, request adguard.CheckConfigRequest) (*adguard.CheckConfigResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for InstallCheckConfig")
	}

	var r0 *adguard.CheckConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.CheckConfigRequest) (*adguard.CheckConfigResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.CheckConfigRequest) *adguard.CheckConfigResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.CheckConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.CheckConfigRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInstallService_InstallCheckConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallCheckConfig'
type MockInstallService_InstallCheckConfig_Call struct {
	*mock.Call
}

// InstallCheckConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.CheckConfigRequest
func (_e *MockInstallService_Expecter) InstallCheckConfig(ctx any, request any) *MockInstallService_InstallCheckConfig_Call {
	return &MockInstallService_InstallCheckConfig_Call{Call: _e.mock.On("InstallCheckConfig", ctx, request)}
}

func (_c *MockInstallService_InstallCheckConfig_Call) Run(run func(ctx context.Context, request adguard.CheckConfigRequest)) *MockInstallService_InstallCheckConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.CheckConfigRequest
		if args[1] != nil {
			arg1 = args[1].(adguard.CheckConfigRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInstallService_InstallCheckConfig_Call) Return(checkConfigResponse *adguard.CheckConfigResponse, err error) *MockInstallService_InstallCheckConfig_Call {
	_c.Call.Return(checkConfigResponse, err)
	return _c
}

func (_c *MockInstallService_InstallCheckConfig_Call) RunAndReturn(run func(ctx context.Context, request adguard.CheckConfigRequest) (*adguard.CheckConfigResponse, error)) *MockInstallService_InstallCheckConfig_Call {
	_c.Call.Return(run)
	return _c
}

// InstallConfigure provides a mock function for the type MockInstallService
func (_mock *MockInstallService) InstallConfigure(ctx context.Context, configuration adguard.InitialConfiguration) error {
	ret := _mock.Called(ctx, configuration)

	if len(ret) == 0 {
		panic("no return value specified for InstallConfigure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.InitialConfiguration) error); ok {
		r0 = returnFunc(ctx, configuration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallService_InstallConfigure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallConfigure'
type MockInstallService_InstallConfigure_Call struct {
	*mock.Call
}

// InstallConfigure is a helper method to define mock.On call
//   - ctx context.Context
//   - configuration adguard.InitialConfiguration
func (_e *MockInstallService_Expecter) InstallConfigure(ctx any, configuration any) *MockInstallService_InstallConfigure_Call {
	return &MockInstallService_InstallConfigure_Call{Call: _e.mock.On("InstallConfigure", ctx, configuration)}
}

func (_c *MockInstallService_InstallConfigure_Call) Run(run func(ctx context.Context, configuration adguard.InitialConfiguration)) *MockInstallService_InstallConfigure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.InitialConfiguration
		if args[1] != nil {
			arg1 = args[1].(adguard.InitialConfiguration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInstallService_InstallConfigure_Call) Return(err error) *MockInstallService_InstallConfigure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallService_InstallConfigure_Call) RunAndReturn(run func(ctx context.Context, configuration adguard.InitialConfiguration) error) *MockInstallService_InstallConfigure_Call {
	_c.Call.Return(run)
	return _c
}

// InstallGetAddresses provides a mock function for the type MockInstallService
func (_mock *MockInstallService) InstallGetAddresses(ctx context.Context) (*adguard.AddressesInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InstallGetAddresses")
	}

	var r0 *adguard.AddressesInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.AddressesInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.AddressesInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.AddressesInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInstallService_InstallGetAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallGetAddresses'
type MockInstallService_InstallGetAddresses_Call struct {
	*mock.Call
}

// InstallGetAddresses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstallService_Expecter) InstallGetAddresses(ctx any) *MockInstallService_InstallGetAddresses_Call {
	return &MockInstallService_InstallGetAddresses_Call{Call: _e.mock.On("InstallGetAddresses", ctx)}
}

func (_c *MockInstallService_InstallGetAddresses_Call) Run(run func(ctx context.Context)) *MockInstallService_InstallGetAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallService_InstallGetAddresses_Call) Return(addressesInfo *adguard.AddressesInfo, err error) *MockInstallService_InstallGetAddresses_Call {
	_c.Call.Return(addressesInfo, err)
	return _c
}

func (_c *MockInstallService_InstallGetAddresses_Call) RunAndReturn(run func(ctx context.Context) (*adguard.AddressesInfo, error)) *MockInstallService_InstallGetAddresses_Call {
	_c.Call.Return(run)
	return _c
}
