/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMobileConfigService creates a new instance of MockMobileConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMobileConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMobileConfigService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMobileConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMobileConfigService is an autogenerated mock type for the MobileConfigService type
type MockMobileConfigService struct {
	mock.Mock
}

type MockMobileConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMobileConfigService) EXPECT() *MockMobileConfigService_Expecter {
	return &MockMobileConfigService_Expecter{mock: &_m.Mock}
}

// DownloadDoH provides a mock function for the type MockMobileConfigService
func (_mock *MockMobileConfigService) DownloadDoH(ctx context.Context, request adguard.MobileConfigRequest) (adguard.Artifact, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DownloadDoH")
	}

	var r0 adguard.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.MobileConfigRequest) (adguard.Artifact, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.MobileConfigRequest) adguard.Artifact); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(adguard.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.MobileConfigRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMobileConfigService_DownloadDoH_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadDoH'
type MockMobileConfigService_DownloadDoH_Call struct {
	*mock.Call
}

// DownloadDoH is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.MobileConfigRequest
func (_e *MockMobileConfigService_Expecter) DownloadDoH(ctx any, request any) *MockMobileConfigService_DownloadDoH_Call {
	return &MockMobileConfigService_DownloadDoH_Call{Call: _e.mock.On("DownloadDoH", ctx, request)}
}

func (_c *MockMobileConfigService_DownloadDoH_Call) Run(run func(ctx context.Context, request adguard.MobileConfigRequest)) *MockMobileConfigService_DownloadDoH_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.MobileConfigRequest
		if args[1] != nil {
			arg1 = args[1].(adguard.MobileConfigRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMobileConfigService_DownloadDoH_Call) Return(artifact adguard.Artifact, err error) *MockMobileConfigService_DownloadDoH_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockMobileConfigService_DownloadDoH_Call) RunAndReturn(run func(ctx context.Context, request adguard.MobileConfigRequest) (adguard.Artifact, error)) *MockMobileConfigService_DownloadDoH_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadDoT provides a mock function for the type MockMobileConfigService
func (_mock *MockMobileConfigService) DownloadDoT(ctx context.Context, request adguard.MobileConfigRequest) (adguard.Artifact, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DownloadDoT")
	}

	var r0 adguard.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.MobileConfigRequest) (adguard.Artifact, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.MobileConfigRequest) adguard.Artifact); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(adguard.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.MobileConfigRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMobileConfigService_DownloadDoT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadDoT'
type MockMobileConfigService_DownloadDoT_Call struct {
	*mock.Call
}

// DownloadDoT is a helper method to define mock.On call
//   - ctx context.Context
//   - request adguard.MobileConfigRequest
func (_e *MockMobileConfigService_Expecter) DownloadDoT(ctx any, request any) *MockMobileConfigService_DownloadDoT_Call {
	return &MockMobileConfigService_DownloadDoT_Call{Call: _e.mock.On("DownloadDoT", ctx, request)}
}

func (_c *MockMobileConfigService_DownloadDoT_Call) Run(run func(ctx context.Context, request adguard.MobileConfigRequest)) *MockMobileConfigService_DownloadDoT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.MobileConfigRequest
		if args[1] != nil {
			arg1 = args[1].(adguard.MobileConfigRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMobileConfigService_DownloadDoT_Call) Return(artifact adguard.Artifact, err error) *MockMobileConfigService_DownloadDoT_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockMobileConfigService_DownloadDoT_Call) RunAndReturn(run func(ctx context.Context, request adguard.MobileConfigRequest) (adguard.Artifact, error)) *MockMobileConfigService_DownloadDoT_Call {
	_c.Call.Return(run)
	return _c
}
