/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileService creates a new instance of MockProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProfileService is an autogenerated mock type for the ProfileService type
type MockProfileService struct {
	mock.Mock
}

type MockProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileService) EXPECT() *MockProfileService_Expecter {
	return &MockProfileService_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetProfile(ctx context.Context) (*adguard.Profile, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *adguard.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.Profile, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.Profile); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockProfileService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfileService_Expecter) GetProfile(ctx any) *MockProfileService_GetProfile_Call {
	return &MockProfileService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx)}
}

func (_c *MockProfileService_GetProfile_Call) Run(run func(ctx context.Context)) *MockProfileService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileService_GetProfile_Call) Return(profile *adguard.Profile, err error) *MockProfileService_GetProfile_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileService_GetProfile_Call) RunAndReturn(run func(ctx context.Context) (*adguard.Profile, error)) *MockProfileService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockProfileService
func (_mock *MockProfileService) UpdateProfile(ctx context.Context, profile adguard.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockProfileService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profile adguard.Profile
func (_e *MockProfileService_Expecter) UpdateProfile(ctx any, profile any) *MockProfileService_UpdateProfile_Call {
	return &MockProfileService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, profile)}
}

func (_c *MockProfileService_UpdateProfile_Call) Run(run func(ctx context.Context, profile adguard.Profile)) *MockProfileService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.Profile
		if args[1] != nil {
			arg1 = args[1].(adguard.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_UpdateProfile_Call) Return(err error) *MockProfileService_UpdateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, profile adguard.Profile) error) *MockProfileService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
