/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryLogService creates a new instance of MockQueryLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryLogService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockQueryLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockQueryLogService is an autogenerated mock type for the QueryLogService type
type MockQueryLogService struct {
	mock.Mock
}

type MockQueryLogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryLogService) EXPECT() *MockQueryLogService_Expecter {
	return &MockQueryLogService_Expecter{mock: &_m.Mock}
}

// GetQueryLogConfig provides a mock function for the type MockQueryLogService
func (_mock *MockQueryLogService) GetQueryLogConfig(ctx context.Context) (*adguard.QueryLogConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryLogConfig")
	}

	var r0 *adguard.QueryLogConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.QueryLogConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.QueryLogConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.QueryLogConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryLogService_GetQueryLogConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryLogConfig'
type MockQueryLogService_GetQueryLogConfig_Call struct {
	*mock.Call
}

// GetQueryLogConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueryLogService_Expecter) GetQueryLogConfig(ctx any) *MockQueryLogService_GetQueryLogConfig_Call {
	return &MockQueryLogService_GetQueryLogConfig_Call{Call: _e.mock.On("GetQueryLogConfig", ctx)}
}

func (_c *MockQueryLogService_GetQueryLogConfig_Call) Run(run func(ctx context.Context)) *MockQueryLogService_GetQueryLogConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryLogService_GetQueryLogConfig_Call) Return(queryLogConfig *adguard.QueryLogConfig, err error) *MockQueryLogService_GetQueryLogConfig_Call {
	_c.Call.Return(queryLogConfig, err)
	return _c
}

func (_c *MockQueryLogService_GetQueryLogConfig_Call) RunAndReturn(run func(ctx context.Context) (*adguard.QueryLogConfig, error)) *MockQueryLogService_GetQueryLogConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PutQueryLogConfig provides a mock function for the type MockQueryLogService
func (_mock *MockQueryLogService) PutQueryLogConfig(ctx context.Context, config adguard.QueryLogConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for PutQueryLogConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.QueryLogConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryLogService_PutQueryLogConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutQueryLogConfig'
type MockQueryLogService_PutQueryLogConfig_Call struct {
	*mock.Call
}

// PutQueryLogConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.QueryLogConfig
func (_e *MockQueryLogService_Expecter) PutQueryLogConfig(ctx any, config any) *MockQueryLogService_PutQueryLogConfig_Call {
	return &MockQueryLogService_PutQueryLogConfig_Call{Call: _e.mock.On("PutQueryLogConfig", ctx, config)}
}

func (_c *MockQueryLogService_PutQueryLogConfig_Call) Run(run func(ctx context.Context, config adguard.QueryLogConfig)) *MockQueryLogService_PutQueryLogConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.QueryLogConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.QueryLogConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryLogService_PutQueryLogConfig_Call) Return(err error) *MockQueryLogService_PutQueryLogConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryLogService_PutQueryLogConfig_Call) RunAndReturn(run func(ctx context.Context, config adguard.QueryLogConfig) error) *MockQueryLogService_PutQueryLogConfig_Call {
	_c.Call.Return(run)
	return _c
}

// QueryLog provides a mock function for the type MockQueryLogService
func (_mock *MockQueryLogService) QueryLog(ctx context.Context, request *adguard.QueryLogRequest) (*adguard.QueryLog, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for QueryLog")
	}

	var r0 *adguard.QueryLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.QueryLogRequest) (*adguard.QueryLog, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.QueryLogRequest) *adguard.QueryLog); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.QueryLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *adguard.QueryLogRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryLogService_QueryLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryLog'
type MockQueryLogService_QueryLog_Call struct {
	*mock.Call
}

// QueryLog is a helper method to define mock.On call
//   - ctx context.Context
//   - request *adguard.QueryLogRequest
func (_e *MockQueryLogService_Expecter) QueryLog(ctx any, request any) *MockQueryLogService_QueryLog_Call {
	return &MockQueryLogService_QueryLog_Call{Call: _e.mock.On("QueryLog", ctx, request)}
}

func (_c *MockQueryLogService_QueryLog_Call) Run(run func(ctx context.Context, request *adguard.QueryLogRequest)) *MockQueryLogService_QueryLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.QueryLogRequest
		if args[1] != nil {
			arg1 = args[1].(*adguard.QueryLogRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryLogService_QueryLog_Call) Return(queryLog *adguard.QueryLog, err error) *MockQueryLogService_QueryLog_Call {
	_c.Call.Return(queryLog, err)
	return _c
}

func (_c *MockQueryLogService_QueryLog_Call) RunAndReturn(run func(ctx context.Context, request *adguard.QueryLogRequest) (*adguard.QueryLog, error)) *MockQueryLogService_QueryLog_Call {
	_c.Call.Return(run)
	return _c
}

// QueryLogClear provides a mock function for the type MockQueryLogService
func (_mock *MockQueryLogService) QueryLogClear(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for QueryLogClear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryLogService_QueryLogClear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryLogClear'
type MockQueryLogService_QueryLogClear_Call struct {
	*mock.Call
}

// QueryLogClear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueryLogService_Expecter) QueryLogClear(ctx any) *MockQueryLogService_QueryLogClear_Call {
	return &MockQueryLogService_QueryLogClear_Call{Call: _e.mock.On("QueryLogClear", ctx)}
}

func (_c *MockQueryLogService_QueryLogClear_Call) Run(run func(ctx context.Context)) *MockQueryLogService_QueryLogClear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryLogService_QueryLogClear_Call) Return(err error) *MockQueryLogService_QueryLogClear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryLogService_QueryLogClear_Call) RunAndReturn(run func(ctx context.Context) error) *MockQueryLogService_QueryLogClear_Call {
	_c.Call.Return(run)
	return _c
}

// QueryLogConfig provides a mock function for the type MockQueryLogService
func (_mock *MockQueryLogService) QueryLogConfig(ctx context.Context, config adguard.QueryLogConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for QueryLogConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.QueryLogConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryLogService_QueryLogConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryLogConfig'
type MockQueryLogService_QueryLogConfig_Call struct {
	*mock.Call
}

// QueryLogConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.QueryLogConfig
func (_e *MockQueryLogService_Expecter) QueryLogConfig(ctx any, config any) *MockQueryLogService_QueryLogConfig_Call {
	return &MockQueryLogService_QueryLogConfig_Call{Call: _e.mock.On("QueryLogConfig", ctx, config)}
}

func (_c *MockQueryLogService_QueryLogConfig_Call) Run(run func(ctx context.Context, config adguard.QueryLogConfig)) *MockQueryLogService_QueryLogConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.QueryLogConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.QueryLogConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryLogService_QueryLogConfig_Call) Return(err error) *MockQueryLogService_QueryLogConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryLogService_QueryLogConfig_Call) RunAndReturn(run func(ctx context.Context, config adguard.QueryLogConfig) error) *MockQueryLogService_QueryLogConfig_Call {
	_c.Call.Return(run)
	return _c
}

// QueryLogInfo provides a mock function for the type MockQueryLogService
func (_mock *MockQueryLogService) QueryLogInfo(ctx context.Context) (*adguard.QueryLogConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for QueryLogInfo")
	}

	var r0 *adguard.QueryLogConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.QueryLogConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.QueryLogConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.QueryLogConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryLogService_QueryLogInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryLogInfo'
type MockQueryLogService_QueryLogInfo_Call struct {
	*mock.Call
}

// QueryLogInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueryLogService_Expecter) QueryLogInfo(ctx any) *MockQueryLogService_QueryLogInfo_Call {
	return &MockQueryLogService_QueryLogInfo_Call{Call: _e.mock.On("QueryLogInfo", ctx)}
}

func (_c *MockQueryLogService_QueryLogInfo_Call) Run(run func(ctx context.Context)) *MockQueryLogService_QueryLogInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryLogService_QueryLogInfo_Call) Return(queryLogConfig *adguard.QueryLogConfig, err error) *MockQueryLogService_QueryLogInfo_Call {
	_c.Call.Return(queryLogConfig, err)
	return _c
}

func (_c *MockQueryLogService_QueryLogInfo_Call) RunAndReturn(run func(ctx context.Context) (*adguard.QueryLogConfig, error)) *MockQueryLogService_QueryLogInfo_Call {
	_c.Call.Return(run)
	return _c
}
