/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRewriteService creates a new instance of MockRewriteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRewriteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRewriteService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRewriteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRewriteService is an autogenerated mock type for the RewriteService type
type MockRewriteService struct {
	mock.Mock
}

type MockRewriteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRewriteService) EXPECT() *MockRewriteService_Expecter {
	return &MockRewriteService_Expecter{mock: &_m.Mock}
}

// AddRewriteRule provides a mock function for the type MockRewriteService
func (_mock *MockRewriteService) AddRewriteRule(ctx context.Context, rule adguard.RewriteRule) error {
	ret := _mock.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for AddRewriteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.RewriteRule) error); ok {
		r0 = returnFunc(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRewriteService_AddRewriteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRewriteRule'
type MockRewriteService_AddRewriteRule_Call struct {
	*mock.Call
}

// AddRewriteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule adguard.RewriteRule
func (_e *MockRewriteService_Expecter) AddRewriteRule(ctx any, rule any) *MockRewriteService_AddRewriteRule_Call {
	return &MockRewriteService_AddRewriteRule_Call{Call: _e.mock.On("AddRewriteRule", ctx, rule)}
}

func (_c *MockRewriteService_AddRewriteRule_Call) Run(run func(ctx context.Context, rule adguard.RewriteRule)) *MockRewriteService_AddRewriteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.RewriteRule
		if args[1] != nil {
			arg1 = args[1].(adguard.RewriteRule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRewriteService_AddRewriteRule_Call) Return(err error) *MockRewriteService_AddRewriteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRewriteService_AddRewriteRule_Call) RunAndReturn(run func(ctx context.Context, rule adguard.RewriteRule) error) *MockRewriteService_AddRewriteRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRewriteRule provides a mock function for the type MockRewriteService
func (_mock *MockRewriteService) DeleteRewriteRule(ctx context.Context, rule adguard.RewriteRule) error {
	ret := _mock.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRewriteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.RewriteRule) error); ok {
		r0 = returnFunc(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRewriteService_DeleteRewriteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRewriteRule'
type MockRewriteService_DeleteRewriteRule_Call struct {
	*mock.Call
}

// DeleteRewriteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule adguard.RewriteRule
func (_e *MockRewriteService_Expecter) DeleteRewriteRule(ctx any, rule any) *MockRewriteService_DeleteRewriteRule_Call {
	return &MockRewriteService_DeleteRewriteRule_Call{Call: _e.mock.On("DeleteRewriteRule", ctx, rule)}
}

func (_c *MockRewriteService_DeleteRewriteRule_Call) Run(run func(ctx context.Context, rule adguard.RewriteRule)) *MockRewriteService_DeleteRewriteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.RewriteRule
		if args[1] != nil {
			arg1 = args[1].(adguard.RewriteRule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRewriteService_DeleteRewriteRule_Call) Return(err error) *MockRewriteService_DeleteRewriteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRewriteService_DeleteRewriteRule_Call) RunAndReturn(run func(ctx context.Context, rule adguard.RewriteRule) error) *MockRewriteService_DeleteRewriteRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetRewriteSettings provides a mock function for the type MockRewriteService
func (_mock *MockRewriteService) GetRewriteSettings(ctx context.Context) (*adguard.RewriteSettings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRewriteSettings")
	}

	var r0 *adguard.RewriteSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.RewriteSettings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.RewriteSettings); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.RewriteSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRewriteService_GetRewriteSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRewriteSettings'
type MockRewriteService_GetRewriteSettings_Call struct {
	*mock.Call
}

// GetRewriteSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRewriteService_Expecter) GetRewriteSettings(ctx any) *MockRewriteService_GetRewriteSettings_Call {
	return &MockRewriteService_GetRewriteSettings_Call{Call: _e.mock.On("GetRewriteSettings", ctx)}
}

func (_c *MockRewriteService_GetRewriteSettings_Call) Run(run func(ctx context.Context)) *MockRewriteService_GetRewriteSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRewriteService_GetRewriteSettings_Call) Return(rewriteSettings *adguard.RewriteSettings, err error) *MockRewriteService_GetRewriteSettings_Call {
	_c.Call.Return(rewriteSettings, err)
	return _c
}

func (_c *MockRewriteService_GetRewriteSettings_Call) RunAndReturn(run func(ctx context.Context) (*adguard.RewriteSettings, error)) *MockRewriteService_GetRewriteSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListRewriteRules provides a mock function for the type MockRewriteService
func (_mock *MockRewriteService) ListRewriteRules(ctx context.Context) ([]adguard.RewriteRule, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRewriteRules")
	}

	var r0 []adguard.RewriteRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]adguard.RewriteRule, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []adguard.RewriteRule); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adguard.RewriteRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRewriteService_ListRewriteRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRewriteRules'
type MockRewriteService_ListRewriteRules_Call struct {
	*mock.Call
}

// ListRewriteRules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRewriteService_Expecter) ListRewriteRules(ctx any) *MockRewriteService_ListRewriteRules_Call {
	return &MockRewriteService_ListRewriteRules_Call{Call: _e.mock.On("ListRewriteRules", ctx)}
}

func (_c *MockRewriteService_ListRewriteRules_Call) Run(run func(ctx context.Context)) *MockRewriteService_ListRewriteRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRewriteService_ListRewriteRules_Call) Return(rewriteRules []adguard.RewriteRule, err error) *MockRewriteService_ListRewriteRules_Call {
	_c.Call.Return(rewriteRules, err)
	return _c
}

func (_c *MockRewriteService_ListRewriteRules_Call) RunAndReturn(run func(ctx context.Context) ([]adguard.RewriteRule, error)) *MockRewriteService_ListRewriteRules_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRewriteRule provides a mock function for the type MockRewriteService
func (_mock *MockRewriteService) UpdateRewriteRule(ctx context.Context, update adguard.RewriteUpdate) error {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRewriteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.RewriteUpdate) error); ok {
		r0 = returnFunc(ctx, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRewriteService_UpdateRewriteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRewriteRule'
type MockRewriteService_UpdateRewriteRule_Call struct {
	*mock.Call
}

// UpdateRewriteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - update adguard.RewriteUpdate
func (_e *MockRewriteService_Expecter) UpdateRewriteRule(ctx any, update any) *MockRewriteService_UpdateRewriteRule_Call {
	return &MockRewriteService_UpdateRewriteRule_Call{Call: _e.mock.On("UpdateRewriteRule", ctx, update)}
}

func (_c *MockRewriteService_UpdateRewriteRule_Call) Run(run func(ctx context.Context, update adguard.RewriteUpdate)) *MockRewriteService_UpdateRewriteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.RewriteUpdate
		if args[1] != nil {
			arg1 = args[1].(adguard.RewriteUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRewriteService_UpdateRewriteRule_Call) Return(err error) *MockRewriteService_UpdateRewriteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRewriteService_UpdateRewriteRule_Call) RunAndReturn(run func(ctx context.Context, update adguard.RewriteUpdate) error) *MockRewriteService_UpdateRewriteRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRewriteSettings provides a mock function for the type MockRewriteService
func (_mock *MockRewriteService) UpdateRewriteSettings(ctx context.Context, settings adguard.RewriteSettings) error {
	ret := _mock.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRewriteSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.RewriteSettings) error); ok {
		r0 = returnFunc(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRewriteService_UpdateRewriteSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRewriteSettings'
type MockRewriteService_UpdateRewriteSettings_Call struct {
	*mock.Call
}

// UpdateRewriteSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - settings adguard.RewriteSettings
func (_e *MockRewriteService_Expecter) UpdateRewriteSettings(ctx any, settings any) *MockRewriteService_UpdateRewriteSettings_Call {
	return &MockRewriteService_UpdateRewriteSettings_Call{Call: _e.mock.On("UpdateRewriteSettings", ctx, settings)}
}

func (_c *MockRewriteService_UpdateRewriteSettings_Call) Run(run func(ctx context.Context, settings adguard.RewriteSettings)) *MockRewriteService_UpdateRewriteSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.RewriteSettings
		if args[1] != nil {
			arg1 = args[1].(adguard.RewriteSettings)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRewriteService_UpdateRewriteSettings_Call) Return(err error) *MockRewriteService_UpdateRewriteSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRewriteService_UpdateRewriteSettings_Call) RunAndReturn(run func(ctx context.Context, settings adguard.RewriteSettings) error) *MockRewriteService_UpdateRewriteSettings_Call {
	_c.Call.Return(run)
	return _c
}
