/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSafetyService creates a new instance of MockSafetyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSafetyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSafetyService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSafetyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSafetyService is an autogenerated mock type for the SafetyService type
type MockSafetyService struct {
	mock.Mock
}

type MockSafetyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSafetyService) EXPECT() *MockSafetyService_Expecter {
	return &MockSafetyService_Expecter{mock: &_m.Mock}
}

// ParentalDisable provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) ParentalDisable(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ParentalDisable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSafetyService_ParentalDisable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParentalDisable'
type MockSafetyService_ParentalDisable_Call struct {
	*mock.Call
}

// ParentalDisable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) ParentalDisable(ctx any) *MockSafetyService_ParentalDisable_Call {
	return &MockSafetyService_ParentalDisable_Call{Call: _e.mock.On("ParentalDisable", ctx)}
}

func (_c *MockSafetyService_ParentalDisable_Call) Run(run func(ctx context.Context)) *MockSafetyService_ParentalDisable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_ParentalDisable_Call) Return(err error) *MockSafetyService_ParentalDisable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSafetyService_ParentalDisable_Call) RunAndReturn(run func(ctx context.Context) error) *MockSafetyService_ParentalDisable_Call {
	_c.Call.Return(run)
	return _c
}

// ParentalEnable provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) ParentalEnable(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ParentalEnable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSafetyService_ParentalEnable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParentalEnable'
type MockSafetyService_ParentalEnable_Call struct {
	*mock.Call
}

// ParentalEnable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) ParentalEnable(ctx any) *MockSafetyService_ParentalEnable_Call {
	return &MockSafetyService_ParentalEnable_Call{Call: _e.mock.On("ParentalEnable", ctx)}
}

func (_c *MockSafetyService_ParentalEnable_Call) Run(run func(ctx context.Context)) *MockSafetyService_ParentalEnable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_ParentalEnable_Call) Return(err error) *MockSafetyService_ParentalEnable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSafetyService_ParentalEnable_Call) RunAndReturn(run func(ctx context.Context) error) *MockSafetyService_ParentalEnable_Call {
	_c.Call.Return(run)
	return _c
}

// ParentalStatus provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) ParentalStatus(ctx context.Context) (*adguard.ParentalStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ParentalStatus")
	}

	var r0 *adguard.ParentalStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.ParentalStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.ParentalStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.ParentalStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSafetyService_ParentalStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParentalStatus'
type MockSafetyService_ParentalStatus_Call struct {
	*mock.Call
}

// ParentalStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) ParentalStatus(ctx any) *MockSafetyService_ParentalStatus_Call {
	return &MockSafetyService_ParentalStatus_Call{Call: _e.mock.On("ParentalStatus", ctx)}
}

func (_c *MockSafetyService_ParentalStatus_Call) Run(run func(ctx context.Context)) *MockSafetyService_ParentalStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_ParentalStatus_Call) Return(parentalStatus *adguard.ParentalStatus, err error) *MockSafetyService_ParentalStatus_Call {
	_c.Call.Return(parentalStatus, err)
	return _c
}

func (_c *MockSafetyService_ParentalStatus_Call) RunAndReturn(run func(ctx context.Context) (*adguard.ParentalStatus, error)) *MockSafetyService_ParentalStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SafebrowsingDisable provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) SafebrowsingDisable(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SafebrowsingDisable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSafetyService_SafebrowsingDisable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafebrowsingDisable'
type MockSafetyService_SafebrowsingDisable_Call struct {
	*mock.Call
}

// SafebrowsingDisable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) SafebrowsingDisable(ctx any) *MockSafetyService_SafebrowsingDisable_Call {
	return &MockSafetyService_SafebrowsingDisable_Call{Call: _e.mock.On("SafebrowsingDisable", ctx)}
}

func (_c *MockSafetyService_SafebrowsingDisable_Call) Run(run func(ctx context.Context)) *MockSafetyService_SafebrowsingDisable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_SafebrowsingDisable_Call) Return(err error) *MockSafetyService_SafebrowsingDisable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSafetyService_SafebrowsingDisable_Call) RunAndReturn(run func(ctx context.Context) error) *MockSafetyService_SafebrowsingDisable_Call {
	_c.Call.Return(run)
	return _c
}

// SafebrowsingEnable provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) SafebrowsingEnable(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SafebrowsingEnable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSafetyService_SafebrowsingEnable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafebrowsingEnable'
type MockSafetyService_SafebrowsingEnable_Call struct {
	*mock.Call
}

// SafebrowsingEnable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) SafebrowsingEnable(ctx any) *MockSafetyService_SafebrowsingEnable_Call {
	return &MockSafetyService_SafebrowsingEnable_Call{Call: _e.mock.On("SafebrowsingEnable", ctx)}
}

func (_c *MockSafetyService_SafebrowsingEnable_Call) Run(run func(ctx context.Context)) *MockSafetyService_SafebrowsingEnable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_SafebrowsingEnable_Call) Return(err error) *MockSafetyService_SafebrowsingEnable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSafetyService_SafebrowsingEnable_Call) RunAndReturn(run func(ctx context.Context) error) *MockSafetyService_SafebrowsingEnable_Call {
	_c.Call.Return(run)
	return _c
}

// SafebrowsingStatus provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) SafebrowsingStatus(ctx context.Context) (*adguard.SafebrowsingStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SafebrowsingStatus")
	}

	var r0 *adguard.SafebrowsingStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.SafebrowsingStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.SafebrowsingStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.SafebrowsingStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSafetyService_SafebrowsingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafebrowsingStatus'
type MockSafetyService_SafebrowsingStatus_Call struct {
	*mock.Call
}

// SafebrowsingStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) SafebrowsingStatus(ctx any) *MockSafetyService_SafebrowsingStatus_Call {
	return &MockSafetyService_SafebrowsingStatus_Call{Call: _e.mock.On("SafebrowsingStatus", ctx)}
}

func (_c *MockSafetyService_SafebrowsingStatus_Call) Run(run func(ctx context.Context)) *MockSafetyService_SafebrowsingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_SafebrowsingStatus_Call) Return(safebrowsingStatus *adguard.SafebrowsingStatus, err error) *MockSafetyService_SafebrowsingStatus_Call {
	_c.Call.Return(safebrowsingStatus, err)
	return _c
}

func (_c *MockSafetyService_SafebrowsingStatus_Call) RunAndReturn(run func(ctx context.Context) (*adguard.SafebrowsingStatus, error)) *MockSafetyService_SafebrowsingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SafesearchDisable provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) SafesearchDisable(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SafesearchDisable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSafetyService_SafesearchDisable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafesearchDisable'
type MockSafetyService_SafesearchDisable_Call struct {
	*mock.Call
}

// SafesearchDisable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) SafesearchDisable(ctx any) *MockSafetyService_SafesearchDisable_Call {
	return &MockSafetyService_SafesearchDisable_Call{Call: _e.mock.On("SafesearchDisable", ctx)}
}

func (_c *MockSafetyService_SafesearchDisable_Call) Run(run func(ctx context.Context)) *MockSafetyService_SafesearchDisable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_SafesearchDisable_Call) Return(err error) *MockSafetyService_SafesearchDisable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSafetyService_SafesearchDisable_Call) RunAndReturn(run func(ctx context.Context) error) *MockSafetyService_SafesearchDisable_Call {
	_c.Call.Return(run)
	return _c
}

// SafesearchEnable provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) SafesearchEnable(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SafesearchEnable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSafetyService_SafesearchEnable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafesearchEnable'
type MockSafetyService_SafesearchEnable_Call struct {
	*mock.Call
}

// SafesearchEnable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) SafesearchEnable(ctx any) *MockSafetyService_SafesearchEnable_Call {
	return &MockSafetyService_SafesearchEnable_Call{Call: _e.mock.On("SafesearchEnable", ctx)}
}

func (_c *MockSafetyService_SafesearchEnable_Call) Run(run func(ctx context.Context)) *MockSafetyService_SafesearchEnable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_SafesearchEnable_Call) Return(err error) *MockSafetyService_SafesearchEnable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSafetyService_SafesearchEnable_Call) RunAndReturn(run func(ctx context.Context) error) *MockSafetyService_SafesearchEnable_Call {
	_c.Call.Return(run)
	return _c
}

// SafesearchSettings provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) SafesearchSettings(ctx context.Context, config adguard.SafeSearchConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for SafesearchSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.SafeSearchConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSafetyService_SafesearchSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafesearchSettings'
type MockSafetyService_SafesearchSettings_Call struct {
	*mock.Call
}

// SafesearchSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.SafeSearchConfig
func (_e *MockSafetyService_Expecter) SafesearchSettings(ctx any, config any) *MockSafetyService_SafesearchSettings_Call {
	return &MockSafetyService_SafesearchSettings_Call{Call: _e.mock.On("SafesearchSettings", ctx, config)}
}

func (_c *MockSafetyService_SafesearchSettings_Call) Run(run func(ctx context.Context, config adguard.SafeSearchConfig)) *MockSafetyService_SafesearchSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.SafeSearchConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.SafeSearchConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSafetyService_SafesearchSettings_Call) Return(err error) *MockSafetyService_SafesearchSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSafetyService_SafesearchSettings_Call) RunAndReturn(run func(ctx context.Context, config adguard.SafeSearchConfig) error) *MockSafetyService_SafesearchSettings_Call {
	_c.Call.Return(run)
	return _c
}

// SafesearchStatus provides a mock function for the type MockSafetyService
func (_mock *MockSafetyService) SafesearchStatus(ctx context.Context) (*adguard.SafeSearchConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SafesearchStatus")
	}

	var r0 *adguard.SafeSearchConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.SafeSearchConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.SafeSearchConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.SafeSearchConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSafetyService_SafesearchStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SafesearchStatus'
type MockSafetyService_SafesearchStatus_Call struct {
	*mock.Call
}

// SafesearchStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSafetyService_Expecter) SafesearchStatus(ctx any) *MockSafetyService_SafesearchStatus_Call {
	return &MockSafetyService_SafesearchStatus_Call{Call: _e.mock.On("SafesearchStatus", ctx)}
}

func (_c *MockSafetyService_SafesearchStatus_Call) Run(run func(ctx context.Context)) *MockSafetyService_SafesearchStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSafetyService_SafesearchStatus_Call) Return(safeSearchConfig *adguard.SafeSearchConfig, err error) *MockSafetyService_SafesearchStatus_Call {
	_c.Call.Return(safeSearchConfig, err)
	return _c
}

func (_c *MockSafetyService_SafesearchStatus_Call) RunAndReturn(run func(ctx context.Context) (*adguard.SafeSearchConfig, error)) *MockSafetyService_SafesearchStatus_Call {
	_c.Call.Return(run)
	return _c
}
