/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerService creates a new instance of MockServerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockServerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockServerService is an autogenerated mock type for the ServerService type
type MockServerService struct {
	mock.Mock
}

type MockServerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerService) EXPECT() *MockServerService_Expecter {
	return &MockServerService_Expecter{mock: &_m.Mock}
}

// ClearCache provides a mock function for the type MockServerService
func (_mock *MockServerService) ClearCache(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerService_ClearCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCache'
type MockServerService_ClearCache_Call struct {
	*mock.Call
}

// ClearCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerService_Expecter) ClearCache(ctx any) *MockServerService_ClearCache_Call {
	return &MockServerService_ClearCache_Call{Call: _e.mock.On("ClearCache", ctx)}
}

func (_c *MockServerService_ClearCache_Call) Run(run func(ctx context.Context)) *MockServerService_ClearCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerService_ClearCache_Call) Return(err error) *MockServerService_ClearCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerService_ClearCache_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerService_ClearCache_Call {
	_c.Call.Return(run)
	return _c
}

// SetProtection provides a mock function for the type MockServerService
func (_mock *MockServerService) SetProtection(ctx context.Context, config adguard.ProtectionConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for SetProtection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.ProtectionConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerService_SetProtection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProtection'
type MockServerService_SetProtection_Call struct {
	*mock.Call
}

// SetProtection is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.ProtectionConfig
func (_e *MockServerService_Expecter) SetProtection(ctx any, config any) *MockServerService_SetProtection_Call {
	return &MockServerService_SetProtection_Call{Call: _e.mock.On("SetProtection", ctx, config)}
}

func (_c *MockServerService_SetProtection_Call) Run(run func(ctx context.Context, config adguard.ProtectionConfig)) *MockServerService_SetProtection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.ProtectionConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.ProtectionConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerService_SetProtection_Call) Return(err error) *MockServerService_SetProtection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerService_SetProtection_Call) RunAndReturn(run func(ctx context.Context, config adguard.ProtectionConfig) error) *MockServerService_SetProtection_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockServerService
func (_mock *MockServerService) Status(ctx context.Context) (*adguard.ServerStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *adguard.ServerStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.ServerStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.ServerStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.ServerStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockServerService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerService_Expecter) Status(ctx any) *MockServerService_Status_Call {
	return &MockServerService_Status_Call{Call: _e.mock.On("Status", ctx)}
}

func (_c *MockServerService_Status_Call) Run(run func(ctx context.Context)) *MockServerService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerService_Status_Call) Return(serverStatus *adguard.ServerStatus, err error) *MockServerService_Status_Call {
	_c.Call.Return(serverStatus, err)
	return _c
}

func (_c *MockServerService_Status_Call) RunAndReturn(run func(ctx context.Context) (*adguard.ServerStatus, error)) *MockServerService_Status_Call {
	_c.Call.Return(run)
	return _c
}
