/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatsService creates a new instance of MockStatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStatsService is an autogenerated mock type for the StatsService type
type MockStatsService struct {
	mock.Mock
}

type MockStatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsService) EXPECT() *MockStatsService_Expecter {
	return &MockStatsService_Expecter{mock: &_m.Mock}
}

// GetStatsConfig provides a mock function for the type MockStatsService
func (_mock *MockStatsService) GetStatsConfig(ctx context.Context) (*adguard.StatsConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsConfig")
	}

	var r0 *adguard.StatsConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.StatsConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.StatsConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.StatsConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatsService_GetStatsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsConfig'
type MockStatsService_GetStatsConfig_Call struct {
	*mock.Call
}

// GetStatsConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsService_Expecter) GetStatsConfig(ctx any) *MockStatsService_GetStatsConfig_Call {
	return &MockStatsService_GetStatsConfig_Call{Call: _e.mock.On("GetStatsConfig", ctx)}
}

func (_c *MockStatsService_GetStatsConfig_Call) Run(run func(ctx context.Context)) *MockStatsService_GetStatsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatsService_GetStatsConfig_Call) Return(statsConfig *adguard.StatsConfig, err error) *MockStatsService_GetStatsConfig_Call {
	_c.Call.Return(statsConfig, err)
	return _c
}

func (_c *MockStatsService_GetStatsConfig_Call) RunAndReturn(run func(ctx context.Context) (*adguard.StatsConfig, error)) *MockStatsService_GetStatsConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PutStatsConfig provides a mock function for the type MockStatsService
func (_mock *MockStatsService) PutStatsConfig(ctx context.Context, config adguard.StatsConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for PutStatsConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.StatsConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatsService_PutStatsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutStatsConfig'
type MockStatsService_PutStatsConfig_Call struct {
	*mock.Call
}

// PutStatsConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.StatsConfig
func (_e *MockStatsService_Expecter) PutStatsConfig(ctx any, config any) *MockStatsService_PutStatsConfig_Call {
	return &MockStatsService_PutStatsConfig_Call{Call: _e.mock.On("PutStatsConfig", ctx, config)}
}

func (_c *MockStatsService_PutStatsConfig_Call) Run(run func(ctx context.Context, config adguard.StatsConfig)) *MockStatsService_PutStatsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.StatsConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.StatsConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatsService_PutStatsConfig_Call) Return(err error) *MockStatsService_PutStatsConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatsService_PutStatsConfig_Call) RunAndReturn(run func(ctx context.Context, config adguard.StatsConfig) error) *MockStatsService_PutStatsConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockStatsService
func (_mock *MockStatsService) Stats(ctx context.Context, request *adguard.StatsRequest) (*adguard.Stats, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 *adguard.Stats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.StatsRequest) (*adguard.Stats, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adguard.StatsRequest) *adguard.Stats); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.Stats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *adguard.StatsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatsService_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockStatsService_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx context.Context
//   - request *adguard.StatsRequest
func (_e *MockStatsService_Expecter) Stats(ctx any, request any) *MockStatsService_Stats_Call {
	return &MockStatsService_Stats_Call{Call: _e.mock.On("Stats", ctx, request)}
}

func (_c *MockStatsService_Stats_Call) Run(run func(ctx context.Context, request *adguard.StatsRequest)) *MockStatsService_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adguard.StatsRequest
		if args[1] != nil {
			arg1 = args[1].(*adguard.StatsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatsService_Stats_Call) Return(stats *adguard.Stats, err error) *MockStatsService_Stats_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockStatsService_Stats_Call) RunAndReturn(run func(ctx context.Context, request *adguard.StatsRequest) (*adguard.Stats, error)) *MockStatsService_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// StatsConfig provides a mock function for the type MockStatsService
func (_mock *MockStatsService) StatsConfig(ctx context.Context, config adguard.StatsConfig) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for StatsConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.StatsConfig) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatsService_StatsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatsConfig'
type MockStatsService_StatsConfig_Call struct {
	*mock.Call
}

// StatsConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.StatsConfig
func (_e *MockStatsService_Expecter) StatsConfig(ctx any, config any) *MockStatsService_StatsConfig_Call {
	return &MockStatsService_StatsConfig_Call{Call: _e.mock.On("StatsConfig", ctx, config)}
}

func (_c *MockStatsService_StatsConfig_Call) Run(run func(ctx context.Context, config adguard.StatsConfig)) *MockStatsService_StatsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.StatsConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.StatsConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatsService_StatsConfig_Call) Return(err error) *MockStatsService_StatsConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatsService_StatsConfig_Call) RunAndReturn(run func(ctx context.Context, config adguard.StatsConfig) error) *MockStatsService_StatsConfig_Call {
	_c.Call.Return(run)
	return _c
}

// StatsInfo provides a mock function for the type MockStatsService
func (_mock *MockStatsService) StatsInfo(ctx context.Context) (*adguard.StatsConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StatsInfo")
	}

	var r0 *adguard.StatsConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.StatsConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.StatsConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.StatsConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatsService_StatsInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatsInfo'
type MockStatsService_StatsInfo_Call struct {
	*mock.Call
}

// StatsInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsService_Expecter) StatsInfo(ctx any) *MockStatsService_StatsInfo_Call {
	return &MockStatsService_StatsInfo_Call{Call: _e.mock.On("StatsInfo", ctx)}
}

func (_c *MockStatsService_StatsInfo_Call) Run(run func(ctx context.Context)) *MockStatsService_StatsInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatsService_StatsInfo_Call) Return(statsConfig *adguard.StatsConfig, err error) *MockStatsService_StatsInfo_Call {
	_c.Call.Return(statsConfig, err)
	return _c
}

func (_c *MockStatsService_StatsInfo_Call) RunAndReturn(run func(ctx context.Context) (*adguard.StatsConfig, error)) *MockStatsService_StatsInfo_Call {
	_c.Call.Return(run)
	return _c
}

// StatsReset provides a mock function for the type MockStatsService
func (_mock *MockStatsService) StatsReset(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StatsReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatsService_StatsReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatsReset'
type MockStatsService_StatsReset_Call struct {
	*mock.Call
}

// StatsReset is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsService_Expecter) StatsReset(ctx any) *MockStatsService_StatsReset_Call {
	return &MockStatsService_StatsReset_Call{Call: _e.mock.On("StatsReset", ctx)}
}

func (_c *MockStatsService_StatsReset_Call) Run(run func(ctx context.Context)) *MockStatsService_StatsReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatsService_StatsReset_Call) Return(err error) *MockStatsService_StatsReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatsService_StatsReset_Call) RunAndReturn(run func(ctx context.Context) error) *MockStatsService_StatsReset_Call {
	_c.Call.Return(run)
	return _c
}
