/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTLSService creates a new instance of MockTLSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTLSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTLSService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTLSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTLSService is an autogenerated mock type for the TLSService type
type MockTLSService struct {
	mock.Mock
}

type MockTLSService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTLSService) EXPECT() *MockTLSService_Expecter {
	return &MockTLSService_Expecter{mock: &_m.Mock}
}

// TLSConfigure provides a mock function for the type MockTLSService
func (_mock *MockTLSService) TLSConfigure(ctx context.Context, config adguard.TLSConfig) (*adguard.TLSConfig, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TLSConfigure")
	}

	var r0 *adguard.TLSConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.TLSConfig) (*adguard.TLSConfig, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.TLSConfig) *adguard.TLSConfig); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.TLSConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.TLSConfig) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTLSService_TLSConfigure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSConfigure'
type MockTLSService_TLSConfigure_Call struct {
	*mock.Call
}

// TLSConfigure is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.TLSConfig
func (_e *MockTLSService_Expecter) TLSConfigure(ctx any, config any) *MockTLSService_TLSConfigure_Call {
	return &MockTLSService_TLSConfigure_Call{Call: _e.mock.On("TLSConfigure", ctx, config)}
}

func (_c *MockTLSService_TLSConfigure_Call) Run(run func(ctx context.Context, config adguard.TLSConfig)) *MockTLSService_TLSConfigure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.TLSConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.TLSConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTLSService_TLSConfigure_Call) Return(tLSConfig *adguard.TLSConfig, err error) *MockTLSService_TLSConfigure_Call {
	_c.Call.Return(tLSConfig, err)
	return _c
}

func (_c *MockTLSService_TLSConfigure_Call) RunAndReturn(run func(ctx context.Context, config adguard.TLSConfig) (*adguard.TLSConfig, error)) *MockTLSService_TLSConfigure_Call {
	_c.Call.Return(run)
	return _c
}

// TLSStatus provides a mock function for the type MockTLSService
func (_mock *MockTLSService) TLSStatus(ctx context.Context) (*adguard.TLSConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TLSStatus")
	}

	var r0 *adguard.TLSConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*adguard.TLSConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *adguard.TLSConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.TLSConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTLSService_TLSStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSStatus'
type MockTLSService_TLSStatus_Call struct {
	*mock.Call
}

// TLSStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTLSService_Expecter) TLSStatus(ctx any) *MockTLSService_TLSStatus_Call {
	return &MockTLSService_TLSStatus_Call{Call: _e.mock.On("TLSStatus", ctx)}
}

func (_c *MockTLSService_TLSStatus_Call) Run(run func(ctx context.Context)) *MockTLSService_TLSStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTLSService_TLSStatus_Call) Return(tLSConfig *adguard.TLSConfig, err error) *MockTLSService_TLSStatus_Call {
	_c.Call.Return(tLSConfig, err)
	return _c
}

func (_c *MockTLSService_TLSStatus_Call) RunAndReturn(run func(ctx context.Context) (*adguard.TLSConfig, error)) *MockTLSService_TLSStatus_Call {
	_c.Call.Return(run)
	return _c
}

// TLSValidate provides a mock function for the type MockTLSService
func (_mock *MockTLSService) TLSValidate(ctx context.Context, config adguard.TLSConfig) (*adguard.TLSConfig, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TLSValidate")
	}

	var r0 *adguard.TLSConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.TLSConfig) (*adguard.TLSConfig, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, adguard.TLSConfig) *adguard.TLSConfig); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.TLSConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, adguard.TLSConfig) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTLSService_TLSValidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSValidate'
type MockTLSService_TLSValidate_Call struct {
	*mock.Call
}

// TLSValidate is a helper method to define mock.On call
//   - ctx context.Context
//   - config adguard.TLSConfig
func (_e *MockTLSService_Expecter) TLSValidate(ctx any, config any) *MockTLSService_TLSValidate_Call {
	return &MockTLSService_TLSValidate_Call{Call: _e.mock.On("TLSValidate", ctx, config)}
}

func (_c *MockTLSService_TLSValidate_Call) Run(run func(ctx context.Context, config adguard.TLSConfig)) *MockTLSService_TLSValidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 adguard.TLSConfig
		if args[1] != nil {
			arg1 = args[1].(adguard.TLSConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTLSService_TLSValidate_Call) Return(tLSConfig *adguard.TLSConfig, err error) *MockTLSService_TLSValidate_Call {
	_c.Call.Return(tLSConfig, err)
	return _c
}

func (_c *MockTLSService_TLSValidate_Call) RunAndReturn(run func(ctx context.Context, config adguard.TLSConfig) (*adguard.TLSConfig, error)) *MockTLSService_TLSValidate_Call {
	_c.Call.Return(run)
	return _c
}
