/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateService creates a new instance of MockUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUpdateService is an autogenerated mock type for the UpdateService type
type MockUpdateService struct {
	mock.Mock
}

type MockUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateService) EXPECT() *MockUpdateService_Expecter {
	return &MockUpdateService_Expecter{mock: &_m.Mock}
}

// BeginUpdate provides a mock function for the type MockUpdateService
func (_mock *MockUpdateService) BeginUpdate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdateService_BeginUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginUpdate'
type MockUpdateService_BeginUpdate_Call struct {
	*mock.Call
}

// BeginUpdate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUpdateService_Expecter) BeginUpdate(ctx any) *MockUpdateService_BeginUpdate_Call {
	return &MockUpdateService_BeginUpdate_Call{Call: _e.mock.On("BeginUpdate", ctx)}
}

func (_c *MockUpdateService_BeginUpdate_Call) Run(run func(ctx context.Context)) *MockUpdateService_BeginUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpdateService_BeginUpdate_Call) Return(err error) *MockUpdateService_BeginUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdateService_BeginUpdate_Call) RunAndReturn(run func(ctx context.Context) error) *MockUpdateService_BeginUpdate_Call {
	_c.Call.Return(run)
	return _c
}
