/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/pkg/adguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVersionService creates a new instance of MockVersionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVersionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVersionService is an autogenerated mock type for the VersionService type
type MockVersionService struct {
	mock.Mock
}

type MockVersionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionService) EXPECT() *MockVersionService_Expecter {
	return &MockVersionService_Expecter{mock: &_m.Mock}
}

// GetVersionInfo provides a mock function for the type MockVersionService
func (_mock *MockVersionService) GetVersionInfo(ctx context.Context, recheckNow *bool) (*adguard.VersionInfo, error) {
	ret := _mock.Called(ctx, recheckNow)

	if len(ret) == 0 {
		panic("no return value specified for GetVersionInfo")
	}

	var r0 *adguard.VersionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bool) (*adguard.VersionInfo, error)); ok {
		return returnFunc(ctx, recheckNow)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *bool) *adguard.VersionInfo); ok {
		r0 = returnFunc(ctx, recheckNow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adguard.VersionInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *bool) error); ok {
		r1 = returnFunc(ctx, recheckNow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionService_GetVersionInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionInfo'
type MockVersionService_GetVersionInfo_Call struct {
	*mock.Call
}

// GetVersionInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - recheckNow *bool
func (_e *MockVersionService_Expecter) GetVersionInfo(ctx any, recheckNow any) *MockVersionService_GetVersionInfo_Call {
	return &MockVersionService_GetVersionInfo_Call{Call: _e.mock.On("GetVersionInfo", ctx, recheckNow)}
}

func (_c *MockVersionService_GetVersionInfo_Call) Run(run func(ctx context.Context, recheckNow *bool)) *MockVersionService_GetVersionInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *bool
		if args[1] != nil {
			arg1 = args[1].(*bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVersionService_GetVersionInfo_Call) Return(versionInfo *adguard.VersionInfo, err error) *MockVersionService_GetVersionInfo_Call {
	_c.Call.Return(versionInfo, err)
	return _c
}

func (_c *MockVersionService_GetVersionInfo_Call) RunAndReturn(run func(ctx context.Context, recheckNow *bool) (*adguard.VersionInfo, error)) *MockVersionService_GetVersionInfo_Call {
	_c.Call.Return(run)
	return _c
}
