/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/agh-cli/internal/config"
	"github.com/nicholas-fedor/agh-cli/internal/instance"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentialConfig creates a new instance of MockCredentialConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialConfig {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCredentialConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCredentialConfig is an autogenerated mock type for the CredentialConfig type
type MockCredentialConfig struct {
	mock.Mock
}

type MockCredentialConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialConfig) EXPECT() *MockCredentialConfig_Expecter {
	return &MockCredentialConfig_Expecter{mock: &_m.Mock}
}

// ClearCredential provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) ClearCredential(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ClearCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialConfig_ClearCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCredential'
type MockCredentialConfig_ClearCredential_Call struct {
	*mock.Call
}

// ClearCredential is a helper method to define mock.On call
//   - name string
func (_e *MockCredentialConfig_Expecter) ClearCredential(name any) *MockCredentialConfig_ClearCredential_Call {
	return &MockCredentialConfig_ClearCredential_Call{Call: _e.mock.On("ClearCredential", name)}
}

func (_c *MockCredentialConfig_ClearCredential_Call) Run(run func(name string)) *MockCredentialConfig_ClearCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialConfig_ClearCredential_Call) Return(err error) *MockCredentialConfig_ClearCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialConfig_ClearCredential_Call) RunAndReturn(run func(name string) error) *MockCredentialConfig_ClearCredential_Call {
	_c.Call.Return(run)
	return _c
}

// ClearLegacyPassword provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) ClearLegacyPassword(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ClearLegacyPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialConfig_ClearLegacyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearLegacyPassword'
type MockCredentialConfig_ClearLegacyPassword_Call struct {
	*mock.Call
}

// ClearLegacyPassword is a helper method to define mock.On call
//   - name string
func (_e *MockCredentialConfig_Expecter) ClearLegacyPassword(name any) *MockCredentialConfig_ClearLegacyPassword_Call {
	return &MockCredentialConfig_ClearLegacyPassword_Call{Call: _e.mock.On("ClearLegacyPassword", name)}
}

func (_c *MockCredentialConfig_ClearLegacyPassword_Call) Run(run func(name string)) *MockCredentialConfig_ClearLegacyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialConfig_ClearLegacyPassword_Call) Return(err error) *MockCredentialConfig_ClearLegacyPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialConfig_ClearLegacyPassword_Call) RunAndReturn(run func(name string) error) *MockCredentialConfig_ClearLegacyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ClearUsername provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) ClearUsername(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ClearUsername")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialConfig_ClearUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearUsername'
type MockCredentialConfig_ClearUsername_Call struct {
	*mock.Call
}

// ClearUsername is a helper method to define mock.On call
//   - name string
func (_e *MockCredentialConfig_Expecter) ClearUsername(name any) *MockCredentialConfig_ClearUsername_Call {
	return &MockCredentialConfig_ClearUsername_Call{Call: _e.mock.On("ClearUsername", name)}
}

func (_c *MockCredentialConfig_ClearUsername_Call) Run(run func(name string)) *MockCredentialConfig_ClearUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialConfig_ClearUsername_Call) Return(err error) *MockCredentialConfig_ClearUsername_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialConfig_ClearUsername_Call) RunAndReturn(run func(name string) error) *MockCredentialConfig_ClearUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Credentials provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) Credentials() config.CredentialsSettings {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Credentials")
	}

	var r0 config.CredentialsSettings
	if returnFunc, ok := ret.Get(0).(func() config.CredentialsSettings); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.CredentialsSettings)
	}
	return r0
}

// MockCredentialConfig_Credentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Credentials'
type MockCredentialConfig_Credentials_Call struct {
	*mock.Call
}

// Credentials is a helper method to define mock.On call
func (_e *MockCredentialConfig_Expecter) Credentials() *MockCredentialConfig_Credentials_Call {
	return &MockCredentialConfig_Credentials_Call{Call: _e.mock.On("Credentials")}
}

func (_c *MockCredentialConfig_Credentials_Call) Run(run func()) *MockCredentialConfig_Credentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredentialConfig_Credentials_Call) Return(credentialsSettings config.CredentialsSettings) *MockCredentialConfig_Credentials_Call {
	_c.Call.Return(credentialsSettings)
	return _c
}

func (_c *MockCredentialConfig_Credentials_Call) RunAndReturn(run func() config.CredentialsSettings) *MockCredentialConfig_Credentials_Call {
	_c.Call.Return(run)
	return _c
}

// Instances provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) Instances() map[string]instance.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Instances")
	}

	var r0 map[string]instance.Config
	if returnFunc, ok := ret.Get(0).(func() map[string]instance.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]instance.Config)
		}
	}
	return r0
}

// MockCredentialConfig_Instances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instances'
type MockCredentialConfig_Instances_Call struct {
	*mock.Call
}

// Instances is a helper method to define mock.On call
func (_e *MockCredentialConfig_Expecter) Instances() *MockCredentialConfig_Instances_Call {
	return &MockCredentialConfig_Instances_Call{Call: _e.mock.On("Instances")}
}

func (_c *MockCredentialConfig_Instances_Call) Run(run func()) *MockCredentialConfig_Instances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredentialConfig_Instances_Call) Return(stringToConfig map[string]instance.Config) *MockCredentialConfig_Instances_Call {
	_c.Call.Return(stringToConfig)
	return _c
}

func (_c *MockCredentialConfig_Instances_Call) RunAndReturn(run func() map[string]instance.Config) *MockCredentialConfig_Instances_Call {
	_c.Call.Return(run)
	return _c
}

// OrderedNames provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) OrderedNames() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderedNames")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockCredentialConfig_OrderedNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderedNames'
type MockCredentialConfig_OrderedNames_Call struct {
	*mock.Call
}

// OrderedNames is a helper method to define mock.On call
func (_e *MockCredentialConfig_Expecter) OrderedNames() *MockCredentialConfig_OrderedNames_Call {
	return &MockCredentialConfig_OrderedNames_Call{Call: _e.mock.On("OrderedNames")}
}

func (_c *MockCredentialConfig_OrderedNames_Call) Run(run func()) *MockCredentialConfig_OrderedNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredentialConfig_OrderedNames_Call) Return(strings []string) *MockCredentialConfig_OrderedNames_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockCredentialConfig_OrderedNames_Call) RunAndReturn(run func() []string) *MockCredentialConfig_OrderedNames_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) Save() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialConfig_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCredentialConfig_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
func (_e *MockCredentialConfig_Expecter) Save() *MockCredentialConfig_Save_Call {
	return &MockCredentialConfig_Save_Call{Call: _e.mock.On("Save")}
}

func (_c *MockCredentialConfig_Save_Call) Run(run func()) *MockCredentialConfig_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredentialConfig_Save_Call) Return(err error) *MockCredentialConfig_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialConfig_Save_Call) RunAndReturn(run func() error) *MockCredentialConfig_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SetCredential provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) SetCredential(name string, ref instance.CredentialRef) error {
	ret := _mock.Called(name, ref)

	if len(ret) == 0 {
		panic("no return value specified for SetCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, instance.CredentialRef) error); ok {
		r0 = returnFunc(name, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialConfig_SetCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCredential'
type MockCredentialConfig_SetCredential_Call struct {
	*mock.Call
}

// SetCredential is a helper method to define mock.On call
//   - name string
//   - ref instance.CredentialRef
func (_e *MockCredentialConfig_Expecter) SetCredential(name any, ref any) *MockCredentialConfig_SetCredential_Call {
	return &MockCredentialConfig_SetCredential_Call{Call: _e.mock.On("SetCredential", name, ref)}
}

func (_c *MockCredentialConfig_SetCredential_Call) Run(run func(name string, ref instance.CredentialRef)) *MockCredentialConfig_SetCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 instance.CredentialRef
		if args[1] != nil {
			arg1 = args[1].(instance.CredentialRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialConfig_SetCredential_Call) Return(err error) *MockCredentialConfig_SetCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialConfig_SetCredential_Call) RunAndReturn(run func(name string, ref instance.CredentialRef) error) *MockCredentialConfig_SetCredential_Call {
	_c.Call.Return(run)
	return _c
}

// SetUsername provides a mock function for the type MockCredentialConfig
func (_mock *MockCredentialConfig) SetUsername(name string, username string) error {
	ret := _mock.Called(name, username)

	if len(ret) == 0 {
		panic("no return value specified for SetUsername")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(name, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialConfig_SetUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUsername'
type MockCredentialConfig_SetUsername_Call struct {
	*mock.Call
}

// SetUsername is a helper method to define mock.On call
//   - name string
//   - username string
func (_e *MockCredentialConfig_Expecter) SetUsername(name any, username any) *MockCredentialConfig_SetUsername_Call {
	return &MockCredentialConfig_SetUsername_Call{Call: _e.mock.On("SetUsername", name, username)}
}

func (_c *MockCredentialConfig_SetUsername_Call) Run(run func(name string, username string)) *MockCredentialConfig_SetUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialConfig_SetUsername_Call) Return(err error) *MockCredentialConfig_SetUsername_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialConfig_SetUsername_Call) RunAndReturn(run func(name string, username string) error) *MockCredentialConfig_SetUsername_Call {
	_c.Call.Return(run)
	return _c
}
