/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEnvReader creates a new instance of MockEnvReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockEnvReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockEnvReader is an autogenerated mock type for the EnvReader type
type MockEnvReader struct {
	mock.Mock
}

type MockEnvReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvReader) EXPECT() *MockEnvReader_Expecter {
	return &MockEnvReader_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type MockEnvReader
func (_mock *MockEnvReader) Lookup(name string) (string, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockEnvReader_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockEnvReader_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - name string
func (_e *MockEnvReader_Expecter) Lookup(name any) *MockEnvReader_Lookup_Call {
	return &MockEnvReader_Lookup_Call{Call: _e.mock.On("Lookup", name)}
}

func (_c *MockEnvReader_Lookup_Call) Run(run func(name string)) *MockEnvReader_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvReader_Lookup_Call) Return(s string, b bool) *MockEnvReader_Lookup_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockEnvReader_Lookup_Call) RunAndReturn(run func(name string) (string, bool)) *MockEnvReader_Lookup_Call {
	_c.Call.Return(run)
	return _c
}
