/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockkeyringProvider creates a new instance of mockkeyringProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockkeyringProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockkeyringProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockkeyringProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockkeyringProvider is an autogenerated mock type for the keyringProvider type
type mockkeyringProvider struct {
	mock.Mock
}

type mockkeyringProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockkeyringProvider) EXPECT() *mockkeyringProvider_Expecter {
	return &mockkeyringProvider_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type mockkeyringProvider
func (_mock *mockkeyringProvider) Delete(service string, key string) error {
	ret := _mock.Called(service, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(service, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkeyringProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockkeyringProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - service string
//   - key string
func (_e *mockkeyringProvider_Expecter) Delete(service any, key any) *mockkeyringProvider_Delete_Call {
	return &mockkeyringProvider_Delete_Call{Call: _e.mock.On("Delete", service, key)}
}

func (_c *mockkeyringProvider_Delete_Call) Run(run func(service string, key string)) *mockkeyringProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockkeyringProvider_Delete_Call) Return(err error) *mockkeyringProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkeyringProvider_Delete_Call) RunAndReturn(run func(service string, key string) error) *mockkeyringProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type mockkeyringProvider
func (_mock *mockkeyringProvider) DeleteAll(service string) error {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(service)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkeyringProvider_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type mockkeyringProvider_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - service string
func (_e *mockkeyringProvider_Expecter) DeleteAll(service any) *mockkeyringProvider_DeleteAll_Call {
	return &mockkeyringProvider_DeleteAll_Call{Call: _e.mock.On("DeleteAll", service)}
}

func (_c *mockkeyringProvider_DeleteAll_Call) Run(run func(service string)) *mockkeyringProvider_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkeyringProvider_DeleteAll_Call) Return(err error) *mockkeyringProvider_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkeyringProvider_DeleteAll_Call) RunAndReturn(run func(service string) error) *mockkeyringProvider_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockkeyringProvider
func (_mock *mockkeyringProvider) Get(service string, key string) (string, error) {
	ret := _mock.Called(service, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(service, key)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(service, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(service, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkeyringProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockkeyringProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - service string
//   - key string
func (_e *mockkeyringProvider_Expecter) Get(service any, key any) *mockkeyringProvider_Get_Call {
	return &mockkeyringProvider_Get_Call{Call: _e.mock.On("Get", service, key)}
}

func (_c *mockkeyringProvider_Get_Call) Run(run func(service string, key string)) *mockkeyringProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockkeyringProvider_Get_Call) Return(s string, err error) *mockkeyringProvider_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockkeyringProvider_Get_Call) RunAndReturn(run func(service string, key string) (string, error)) *mockkeyringProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type mockkeyringProvider
func (_mock *mockkeyringProvider) Set(service string, key string, secret string) error {
	ret := _mock.Called(service, key, secret)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(service, key, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkeyringProvider_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockkeyringProvider_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - service string
//   - key string
//   - secret string
func (_e *mockkeyringProvider_Expecter) Set(service any, key any, secret any) *mockkeyringProvider_Set_Call {
	return &mockkeyringProvider_Set_Call{Call: _e.mock.On("Set", service, key, secret)}
}

func (_c *mockkeyringProvider_Set_Call) Run(run func(service string, key string, secret string)) *mockkeyringProvider_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockkeyringProvider_Set_Call) Return(err error) *mockkeyringProvider_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkeyringProvider_Set_Call) RunAndReturn(run func(service string, key string, secret string) error) *mockkeyringProvider_Set_Call {
	_c.Call.Return(run)
	return _c
}
