/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Backend provides a mock function for the type MockStore
func (_mock *MockStore) Backend() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Backend")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStore_Backend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backend'
type MockStore_Backend_Call struct {
	*mock.Call
}

// Backend is a helper method to define mock.On call
func (_e *MockStore_Expecter) Backend() *MockStore_Backend_Call {
	return &MockStore_Backend_Call{Call: _e.mock.On("Backend")}
}

func (_c *MockStore_Backend_Call) Run(run func()) *MockStore_Backend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Backend_Call) Return(s string) *MockStore_Backend_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStore_Backend_Call) RunAndReturn(run func() string) *MockStore_Backend_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStore
func (_mock *MockStore) Delete(ctx context.Context, service string, key string) error {
	ret := _mock.Called(ctx, service, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, service, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - key string
func (_e *MockStore_Expecter) Delete(ctx any, service any, key any) *MockStore_Delete_Call {
	return &MockStore_Delete_Call{Call: _e.mock.On("Delete", ctx, service, key)}
}

func (_c *MockStore_Delete_Call) Run(run func(ctx context.Context, service string, key string)) *MockStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Delete_Call) Return(err error) *MockStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Delete_Call) RunAndReturn(run func(ctx context.Context, service string, key string) error) *MockStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type MockStore
func (_mock *MockStore) DeleteAll(ctx context.Context, service string) error {
	ret := _mock.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, service)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockStore_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
func (_e *MockStore_Expecter) DeleteAll(ctx any, service any) *MockStore_DeleteAll_Call {
	return &MockStore_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, service)}
}

func (_c *MockStore_DeleteAll_Call) Run(run func(ctx context.Context, service string)) *MockStore_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteAll_Call) Return(err error) *MockStore_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteAll_Call) RunAndReturn(run func(ctx context.Context, service string) error) *MockStore_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStore
func (_mock *MockStore) Get(ctx context.Context, service string, key string) (string, error) {
	ret := _mock.Called(ctx, service, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, service, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, service, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, service, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - key string
func (_e *MockStore_Expecter) Get(ctx any, service any, key any) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", ctx, service, key)}
}

func (_c *MockStore_Get_Call) Run(run func(ctx context.Context, service string, key string)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(s string, err error) *MockStore_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(ctx context.Context, service string, key string) (string, error)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockStore
func (_mock *MockStore) Set(ctx context.Context, service string, key string, secret string) error {
	ret := _mock.Called(ctx, service, key, secret)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, service, key, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - key string
//   - secret string
func (_e *MockStore_Expecter) Set(ctx any, service any, key any, secret any) *MockStore_Set_Call {
	return &MockStore_Set_Call{Call: _e.mock.On("Set", ctx, service, key, secret)}
}

func (_c *MockStore_Set_Call) Run(run func(ctx context.Context, service string, key string, secret string)) *MockStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Set_Call) Return(err error) *MockStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Set_Call) RunAndReturn(run func(ctx context.Context, service string, key string, secret string) error) *MockStore_Set_Call {
	_c.Call.Return(run)
	return _c
}
