/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/internal/execution"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperation creates a new instance of MockOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperation[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperation[T] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOperation[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOperation is an autogenerated mock type for the Operation type
type MockOperation[T any] struct {
	mock.Mock
}

type MockOperation_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockOperation[T]) EXPECT() *MockOperation_Expecter[T] {
	return &MockOperation_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockOperation
func (_mock *MockOperation[T]) Execute(ctx context.Context, target execution.Target[T]) error {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, execution.Target[T]) error); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperation_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOperation_Execute_Call[T any] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - target execution.Target[T]
func (_e *MockOperation_Expecter[T]) Execute(ctx any, target any) *MockOperation_Execute_Call[T] {
	return &MockOperation_Execute_Call[T]{Call: _e.mock.On("Execute", ctx, target)}
}

func (_c *MockOperation_Execute_Call[T]) Run(run func(ctx context.Context, target execution.Target[T])) *MockOperation_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 execution.Target[T]
		if args[1] != nil {
			arg1 = args[1].(execution.Target[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperation_Execute_Call[T]) Return(err error) *MockOperation_Execute_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperation_Execute_Call[T]) RunAndReturn(run func(ctx context.Context, target execution.Target[T]) error) *MockOperation_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}
