/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/agh-cli/internal/instance"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentialResolver creates a new instance of MockCredentialResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialResolver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCredentialResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCredentialResolver is an autogenerated mock type for the CredentialResolver type
type MockCredentialResolver struct {
	mock.Mock
}

type MockCredentialResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialResolver) EXPECT() *MockCredentialResolver_Expecter {
	return &MockCredentialResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockCredentialResolver
func (_mock *MockCredentialResolver) Resolve(ctx context.Context, cfg instance.Config) (instance.Config, error) {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 instance.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, instance.Config) (instance.Config, error)); ok {
		return returnFunc(ctx, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, instance.Config) instance.Config); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Get(0).(instance.Config)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, instance.Config) error); ok {
		r1 = returnFunc(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockCredentialResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg instance.Config
func (_e *MockCredentialResolver_Expecter) Resolve(ctx any, cfg any) *MockCredentialResolver_Resolve_Call {
	return &MockCredentialResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, cfg)}
}

func (_c *MockCredentialResolver_Resolve_Call) Run(run func(ctx context.Context, cfg instance.Config)) *MockCredentialResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 instance.Config
		if args[1] != nil {
			arg1 = args[1].(instance.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialResolver_Resolve_Call) Return(config instance.Config, err error) *MockCredentialResolver_Resolve_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockCredentialResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, cfg instance.Config) (instance.Config, error)) *MockCredentialResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
